repos:
-   repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3.12
      args: [--line-length=120]
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      args:
      - "--ignore=E203,E266,E501,W503,F403,F401"
      - "--max-line-length=120"
      - "--max-complexity=20"
      - "--select=B,C,E,F,W,T4,B9"
      - "--exclude=test,docs"
      additional_dependencies: [flake8-bugbear]