developers:
  - Pedro Camargo
  - Jan Zill
  - Jamie Cook
  - Andrew O'Brien
  - Yu-Chu Huang
sponsors:
  - IPEA (2015)

binary source: https://github.com/AequilibraE/aequilibrae/releases/download/0.7.3/binaries.zip