developers:
  - Pedro Camargo
  - Jan Zill
  - Jamie Cook
  - Andrew O'Brien
  - Yu-Chu Huang
sponsors:
  - IPEA (2015)

binary source:
  MacOS: https://github.com/AequilibraE/aequilibrae/releases/download/V0.7.3/binaries.zip
  Linux: https://github.com/AequilibraE/aequilibrae/releases/download/V0.7.3/binaries.zip
  Windows:
    np19: https://github.com/AequilibraE/aequilibrae/releases/download/V0.7.3/windows_binaries_1.19.zip
    np20: https://github.com/AequilibraE/aequilibrae/releases/download/V0.7.3/windows_binaries_1.20.zip
    np21: https://github.com/AequilibraE/aequilibrae/releases/download/V0.7.3/windows_binaries_1.21.zip
    np22: https://github.com/AequilibraE/aequilibrae/releases/download/V0.7.3/windows_binaries_1.22.zip
