developers:
  - Pedro Camargo
  - Yu-Chu Huang
  - Jamie Cook
  - Andrew O'Brien
  - Jan Zill
sponsors:
  - IPEA (2015)

binary source: https://github.com/AequilibraE/aequilibrae/releases/download/0.7.1/binaries.zip