from .compare_scenarios_dialog import CompareScenariosDialog as CompareScenariosDialog
from .create_bandwidths_dialog import CreateBandwidthsDialog as CreateBandwidthsDialog
from .simple_tag_dialog import SimpleTagDialog as SimpleTagDialog
