# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ortools/util/int128.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ortools/util/int128.proto\x12\x13operations_research\"#\n\x06Int128\x12\x0c\n\x04high\x18\x01 \x01(\x03\x12\x0b\n\x03low\x18\x02 \x01(\x04\x42\x31\n\x17\x63om.google.ortools.utilP\x01\xaa\x02\x13Google.OrTools.Utilb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ortools.util.int128_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.google.ortools.utilP\001\252\002\023Google.OrTools.Util'
  _globals['_INT128']._serialized_start=50
  _globals['_INT128']._serialized_end=85
# @@protoc_insertion_point(module_scope)
