FROM mcr.microsoft.com/windows/servercore:ltsc2022  

# Set default shell to PowerShell
SHELL ["PowerShell", "-Command"]

# Install Chocolatey
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Install packages
RUN choco install git 7zip -y
RUN choco install python -y

# Install QGIS
RUN choco install qgis -y
# RUN powershell -NoProfile -InputFormat None -Command "choco install qgis-ltr --version=3.34.11 -y"

# # Make sure that ssl certs are available in python
# RUN powershell -NoProfile -InputFormat None -Command "certutil -generateSSTFromWU roots.sst ; certutil -addstore -f root roots.sst ; del roots.sst"
