FROM mcr.microsoft.com/windows/servercore:ltsc2022  

# Set default shell to PowerShell
SHELL ["PowerShell", "-Command"]

WORKDIR C:/qgis_install

# Baixar o QGIS
RUN Invoke-WebRequest -Uri "https://download.osgeo.org/qgis/windows/QGIS-OSGeo4W-3.34.11-1.msi" -OutFile "qgis_installer.msi"

# Instalar o QGIS utilizando o msiexec
RUN Start-Process msiexec.exe -ArgumentList '/i', 'C:\qgis_install\qgis_installer.msi', '/quiet', '/norestart' -NoNewWindow -Wait

# Remover o arquivo MSI após a instalação
RUN Remove-Item -Force "C:\qgis_install\qgis_installer.msi"
