# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ortools/constraint_solver/routing_ils.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ortools.constraint_solver import routing_enums_pb2 as ortools_dot_constraint__solver_dot_routing__enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+ortools/constraint_solver/routing_ils.proto\x12\x13operations_research\x1a-ortools/constraint_solver/routing_enums.proto\"F\n\x0cRuinStrategy\"6\n\x05Value\x12\t\n\x05UNSET\x10\x00\x12\"\n\x1eSPATIALLY_CLOSE_ROUTES_REMOVAL\x10\x01\"\xc0\x01\n\x16RuinRecreateParameters\x12>\n\rruin_strategy\x18\x01 \x01(\x0e\x32\'.operations_research.RuinStrategy.Value\x12K\n\x11recreate_strategy\x18\x02 \x01(\x0e\x32\x30.operations_research.FirstSolutionStrategy.Value\x12\x19\n\x11num_ruined_routes\x18\x03 \x01(\r\"A\n\x14PerturbationStrategy\")\n\x05Value\x12\t\n\x05UNSET\x10\x00\x12\x15\n\x11RUIN_AND_RECREATE\x10\x01\"<\n\x12\x41\x63\x63\x65ptanceStrategy\"&\n\x05Value\x12\t\n\x05UNSET\x10\x00\x12\x12\n\x0eGREEDY_DESCENT\x10\x01\"\xae\x02\n\x1dIteratedLocalSearchParameters\x12N\n\x15perturbation_strategy\x18\x01 \x01(\x0e\x32/.operations_research.PerturbationStrategy.Value\x12M\n\x18ruin_recreate_parameters\x18\x02 \x01(\x0b\x32+.operations_research.RuinRecreateParameters\x12\"\n\x1aimprove_perturbed_solution\x18\x03 \x01(\x08\x12J\n\x13\x61\x63\x63\x65ptance_strategy\x18\x04 \x01(\x0e\x32-.operations_research.AcceptanceStrategy.Valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ortools.constraint_solver.routing_ils_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUINSTRATEGY']._serialized_start=115
  _globals['_RUINSTRATEGY']._serialized_end=185
  _globals['_RUINSTRATEGY_VALUE']._serialized_start=131
  _globals['_RUINSTRATEGY_VALUE']._serialized_end=185
  _globals['_RUINRECREATEPARAMETERS']._serialized_start=188
  _globals['_RUINRECREATEPARAMETERS']._serialized_end=380
  _globals['_PERTURBATIONSTRATEGY']._serialized_start=382
  _globals['_PERTURBATIONSTRATEGY']._serialized_end=447
  _globals['_PERTURBATIONSTRATEGY_VALUE']._serialized_start=406
  _globals['_PERTURBATIONSTRATEGY_VALUE']._serialized_end=447
  _globals['_ACCEPTANCESTRATEGY']._serialized_start=449
  _globals['_ACCEPTANCESTRATEGY']._serialized_end=509
  _globals['_ACCEPTANCESTRATEGY_VALUE']._serialized_start=471
  _globals['_ACCEPTANCESTRATEGY_VALUE']._serialized_end=509
  _globals['_ITERATEDLOCALSEARCHPARAMETERS']._serialized_start=512
  _globals['_ITERATEDLOCALSEARCHPARAMETERS']._serialized_end=814
# @@protoc_insertion_point(module_scope)
