# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_apply_gravity.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apply_gravity(object):
    def setupUi(self, apply_gravity):
        apply_gravity.setObjectName(_fromUtf8("apply_gravity"))
        apply_gravity.resize(239, 388)
        self.r_2 = QtGui.QToolBox(apply_gravity)
        self.r_2.setGeometry(QtCore.QRect(10, 10, 220, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.r_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.r_2.setFont(font)
        self.r_2.setObjectName(_fromUtf8("r_2"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 220, 150))
        self.page.setObjectName(_fromUtf8("page"))
        self.but_load_rows = QtGui.QPushButton(self.page)
        self.but_load_rows.setGeometry(QtCore.QRect(10, 110, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_rows.setFont(font)
        self.but_load_rows.setObjectName(_fromUtf8("but_load_rows"))
        self.report_prod = QtGui.QTextEdit(self.page)
        self.report_prod.setGeometry(QtCore.QRect(5, 40, 210, 60))
        self.report_prod.setObjectName(_fromUtf8("report_prod"))
        self.lbl_prod = QtGui.QLabel(self.page)
        self.lbl_prod.setGeometry(QtCore.QRect(189, 0, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lbl_prod.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wingdings 2"))
        font.setPointSize(36)
        self.lbl_prod.setFont(font)
        self.lbl_prod.setObjectName(_fromUtf8("lbl_prod"))
        self.r_2.addItem(self.page, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 220, 150))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.but_load_columns = QtGui.QPushButton(self.page_3)
        self.but_load_columns.setGeometry(QtCore.QRect(10, 110, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_columns.setFont(font)
        self.but_load_columns.setObjectName(_fromUtf8("but_load_columns"))
        self.report_atra = QtGui.QTextEdit(self.page_3)
        self.report_atra.setGeometry(QtCore.QRect(5, 40, 210, 60))
        self.report_atra.setObjectName(_fromUtf8("report_atra"))
        self.lbl_atra = QtGui.QLabel(self.page_3)
        self.lbl_atra.setGeometry(QtCore.QRect(189, 0, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lbl_atra.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wingdings 2"))
        font.setPointSize(36)
        self.lbl_atra.setFont(font)
        self.lbl_atra.setObjectName(_fromUtf8("lbl_atra"))
        self.r_2.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 220, 150))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.but_load_impedance = QtGui.QPushButton(self.page_4)
        self.but_load_impedance.setGeometry(QtCore.QRect(10, 110, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_impedance.setFont(font)
        self.but_load_impedance.setObjectName(_fromUtf8("but_load_impedance"))
        self.report_matrix = QtGui.QTextEdit(self.page_4)
        self.report_matrix.setGeometry(QtCore.QRect(5, 40, 210, 60))
        self.report_matrix.setObjectName(_fromUtf8("report_matrix"))
        self.lbl_imped = QtGui.QLabel(self.page_4)
        self.lbl_imped.setGeometry(QtCore.QRect(189, 0, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lbl_imped.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wingdings 2"))
        font.setPointSize(36)
        self.lbl_imped.setFont(font)
        self.lbl_imped.setObjectName(_fromUtf8("lbl_imped"))
        self.r_2.addItem(self.page_4, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 220, 150))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.radio_gamma = QtGui.QRadioButton(self.page_2)
        self.radio_gamma.setGeometry(QtCore.QRect(20, 10, 161, 16))
        self.radio_gamma.setObjectName(_fromUtf8("radio_gamma"))
        self.radio_expo = QtGui.QRadioButton(self.page_2)
        self.radio_expo.setGeometry(QtCore.QRect(20, 37, 161, 16))
        self.radio_expo.setObjectName(_fromUtf8("radio_expo"))
        self.radio_power = QtGui.QRadioButton(self.page_2)
        self.radio_power.setGeometry(QtCore.QRect(20, 64, 161, 16))
        self.radio_power.setObjectName(_fromUtf8("radio_power"))
        self.radio_friction = QtGui.QRadioButton(self.page_2)
        self.radio_friction.setGeometry(QtCore.QRect(20, 91, 161, 16))
        self.radio_friction.setObjectName(_fromUtf8("radio_friction"))
        self.but_select_model_file = QtGui.QPushButton(self.page_2)
        self.but_select_model_file.setGeometry(QtCore.QRect(10, 115, 95, 30))
        self.but_select_model_file.setObjectName(_fromUtf8("but_select_model_file"))
        self.but_manual_input = QtGui.QPushButton(self.page_2)
        self.but_manual_input.setGeometry(QtCore.QRect(115, 115, 95, 30))
        self.but_manual_input.setObjectName(_fromUtf8("but_manual_input"))
        self.lbl_par = QtGui.QLabel(self.page_2)
        self.lbl_par.setGeometry(QtCore.QRect(189, 0, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lbl_par.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wingdings 2"))
        font.setPointSize(36)
        self.lbl_par.setFont(font)
        self.lbl_par.setObjectName(_fromUtf8("lbl_par"))
        self.r_2.addItem(self.page_2, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 220, 150))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.but_choose_output_name = QtGui.QPushButton(self.page_5)
        self.but_choose_output_name.setGeometry(QtCore.QRect(226, 140, 140, 25))
        self.but_choose_output_name.setObjectName(_fromUtf8("but_choose_output_name"))
        self.lbl_output = QtGui.QLabel(self.page_5)
        self.lbl_output.setGeometry(QtCore.QRect(189, 0, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lbl_output.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wingdings 2"))
        font.setPointSize(36)
        self.lbl_output.setFont(font)
        self.lbl_output.setObjectName(_fromUtf8("lbl_output"))
        self.report_output = QtGui.QTextEdit(self.page_5)
        self.report_output.setGeometry(QtCore.QRect(5, 40, 210, 60))
        self.report_output.setObjectName(_fromUtf8("report_output"))
        self.but_select_output = QtGui.QPushButton(self.page_5)
        self.but_select_output.setGeometry(QtCore.QRect(10, 110, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_select_output.setFont(font)
        self.but_select_output.setObjectName(_fromUtf8("but_select_output"))
        self.r_2.addItem(self.page_5, _fromUtf8(""))
        self.lbl_funding2 = QtGui.QLabel(apply_gravity)
        self.lbl_funding2.setGeometry(QtCore.QRect(100, 358, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_funding2.setFont(font)
        self.lbl_funding2.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_funding2.setObjectName(_fromUtf8("lbl_funding2"))
        self.progressbar = QtGui.QProgressBar(apply_gravity)
        self.progressbar.setEnabled(True)
        self.progressbar.setGeometry(QtCore.QRect(10, 357, 211, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar.setPalette(palette)
        self.progressbar.setProperty("value", 0)
        self.progressbar.setTextVisible(True)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))
        self.lbl_funding1 = QtGui.QLabel(apply_gravity)
        self.lbl_funding1.setGeometry(QtCore.QRect(12, 359, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lbl_funding1.setFont(font)
        self.lbl_funding1.setObjectName(_fromUtf8("lbl_funding1"))
        self.but_apply_gravity = QtGui.QPushButton(apply_gravity)
        self.but_apply_gravity.setGeometry(QtCore.QRect(10, 319, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_apply_gravity.setFont(font)
        self.but_apply_gravity.setObjectName(_fromUtf8("but_apply_gravity"))
        self.progressbar.raise_()
        self.r_2.raise_()
        self.lbl_funding2.raise_()
        self.lbl_funding1.raise_()
        self.but_apply_gravity.raise_()

        self.retranslateUi(apply_gravity)
        self.r_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(apply_gravity)

    def retranslateUi(self, apply_gravity):
        apply_gravity.setWindowTitle(_translate("apply_gravity", "AequilibraE - Apply gravity model", None))
        self.but_load_rows.setText(_translate("apply_gravity", "Load rows vector", None))
        self.report_prod.setHtml(_translate("apply_gravity", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Vector: NOT loaded</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Zones: 0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total demand: 0</p></body></html>", None))
        self.lbl_prod.setText(_translate("apply_gravity", "O", None))
        self.r_2.setItemText(self.r_2.indexOf(self.page), _translate("apply_gravity", "Productions/Origins vector", None))
        self.but_load_columns.setText(_translate("apply_gravity", "Load columns vector", None))
        self.report_atra.setHtml(_translate("apply_gravity", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Vector: NOT loaded</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Zones: 0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total demand: 0</p></body></html>", None))
        self.lbl_atra.setText(_translate("apply_gravity", "O", None))
        self.r_2.setItemText(self.r_2.indexOf(self.page_3), _translate("apply_gravity", "Atractions/Destinations vector", None))
        self.but_load_impedance.setText(_translate("apply_gravity", "Impedance matrix", None))
        self.report_matrix.setHtml(_translate("apply_gravity", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Matrix: NOT loaded</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dimensions: 0</p></body></html>", None))
        self.lbl_imped.setText(_translate("apply_gravity", "O", None))
        self.r_2.setItemText(self.r_2.indexOf(self.page_4), _translate("apply_gravity", "Impedance matrix", None))
        self.radio_gamma.setText(_translate("apply_gravity", "Gamma Function", None))
        self.radio_expo.setText(_translate("apply_gravity", "Negative Exponential", None))
        self.radio_power.setText(_translate("apply_gravity", "Inverse Power", None))
        self.radio_friction.setText(_translate("apply_gravity", "Friction Factors", None))
        self.but_select_model_file.setText(_translate("apply_gravity", "Model file", None))
        self.but_manual_input.setText(_translate("apply_gravity", "Manual input", None))
        self.lbl_par.setText(_translate("apply_gravity", "O", None))
        self.r_2.setItemText(self.r_2.indexOf(self.page_2), _translate("apply_gravity", "Model parameters", None))
        self.but_choose_output_name.setText(_translate("apply_gravity", "Choose Output", None))
        self.lbl_output.setText(_translate("apply_gravity", "O", None))
        self.report_output.setHtml(_translate("apply_gravity", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p></body></html>", None))
        self.but_select_output.setText(_translate("apply_gravity", "Select Output", None))
        self.r_2.setItemText(self.r_2.indexOf(self.page_5), _translate("apply_gravity", "Outputs", None))
        self.lbl_funding2.setText(_translate("apply_gravity", " www.ipea.gov.br", None))
        self.lbl_funding1.setText(_translate("apply_gravity", "Partially funded by", None))
        self.but_apply_gravity.setText(_translate("apply_gravity", "Apply Gravity Model", None))

