# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ConnectingCentroids.ui'
#
# Created: Sat Aug 20 15:18:31 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ConnectingCentroids(object):
    def setupUi(self, ConnectingCentroids):
        ConnectingCentroids.setObjectName(_fromUtf8("ConnectingCentroids"))
        ConnectingCentroids.setWindowModality(QtCore.Qt.NonModal)
        ConnectingCentroids.resize(744, 535)
        self.groupBox = QtGui.QGroupBox(ConnectingCentroids)
        self.groupBox.setGeometry(QtCore.QRect(20, 310, 711, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(338, 108, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.MaxLength = QtGui.QLineEdit(self.groupBox)
        self.MaxLength.setEnabled(False)
        self.MaxLength.setGeometry(QtCore.QRect(205, 108, 71, 20))
        self.MaxLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MaxLength.setObjectName(_fromUtf8("MaxLength"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 80, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.CentroidLayer = QtGui.QComboBox(self.groupBox)
        self.CentroidLayer.setGeometry(QtCore.QRect(130, 30, 560, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CentroidLayer.setFont(font)
        self.CentroidLayer.setObjectName(_fromUtf8("CentroidLayer"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 66, 80, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.CentroidField = QtGui.QComboBox(self.groupBox)
        self.CentroidField.setGeometry(QtCore.QRect(130, 66, 560, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CentroidField.setFont(font)
        self.CentroidField.setObjectName(_fromUtf8("CentroidField"))
        self.IfMaxLength = QtGui.QCheckBox(self.groupBox)
        self.IfMaxLength.setGeometry(QtCore.QRect(20, 110, 191, 17))
        self.IfMaxLength.setObjectName(_fromUtf8("IfMaxLength"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(280, 110, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.NumberConnectors = QtGui.QComboBox(self.groupBox)
        self.NumberConnectors.setGeometry(QtCore.QRect(488, 107, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.NumberConnectors.setFont(font)
        self.NumberConnectors.setObjectName(_fromUtf8("NumberConnectors"))
        self.groupBox_2 = QtGui.QGroupBox(ConnectingCentroids)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 711, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 28, 80, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.LineLayer = QtGui.QComboBox(self.groupBox_2)
        self.LineLayer.setGeometry(QtCore.QRect(130, 28, 560, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LineLayer.setFont(font)
        self.LineLayer.setObjectName(_fromUtf8("LineLayer"))
        self.OutLinks = QtGui.QLineEdit(self.groupBox_2)
        self.OutLinks.setGeometry(QtCore.QRect(130, 69, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OutLinks.setFont(font)
        self.OutLinks.setText(_fromUtf8(""))
        self.OutLinks.setObjectName(_fromUtf8("OutLinks"))
        self.ChooseLineLayer = QtGui.QPushButton(self.groupBox_2)
        self.ChooseLineLayer.setGeometry(QtCore.QRect(20, 67, 101, 23))
        self.ChooseLineLayer.setObjectName(_fromUtf8("ChooseLineLayer"))
        self.progressbar = QtGui.QProgressBar(ConnectingCentroids)
        self.progressbar.setGeometry(QtCore.QRect(30, 470, 191, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar.setPalette(palette)
        self.progressbar.setProperty("value", 0)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))
        self.pushOK = QtGui.QPushButton(ConnectingCentroids)
        self.pushOK.setGeometry(QtCore.QRect(572, 470, 75, 23))
        self.pushOK.setObjectName(_fromUtf8("pushOK"))
        self.pushClose = QtGui.QPushButton(ConnectingCentroids)
        self.pushClose.setGeometry(QtCore.QRect(650, 470, 75, 23))
        self.pushClose.setObjectName(_fromUtf8("pushClose"))
        self.groupBox_3 = QtGui.QGroupBox(ConnectingCentroids)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 140, 711, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 28, 80, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.NodeLayer = QtGui.QComboBox(self.groupBox_3)
        self.NodeLayer.setGeometry(QtCore.QRect(130, 28, 560, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.NodeLayer.setFont(font)
        self.NodeLayer.setObjectName(_fromUtf8("NodeLayer"))
        self.OutNodes = QtGui.QLineEdit(self.groupBox_3)
        self.OutNodes.setGeometry(QtCore.QRect(130, 102, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OutNodes.setFont(font)
        self.OutNodes.setText(_fromUtf8(""))
        self.OutNodes.setObjectName(_fromUtf8("OutNodes"))
        self.ChooseNodeLayer = QtGui.QPushButton(self.groupBox_3)
        self.ChooseNodeLayer.setGeometry(QtCore.QRect(20, 100, 101, 23))
        self.ChooseNodeLayer.setObjectName(_fromUtf8("ChooseNodeLayer"))
        self.SelectedNodes = QtGui.QCheckBox(self.groupBox_3)
        self.SelectedNodes.setGeometry(QtCore.QRect(150, 133, 191, 17))
        self.SelectedNodes.setObjectName(_fromUtf8("SelectedNodes"))
        self.NodeField = QtGui.QComboBox(self.groupBox_3)
        self.NodeField.setGeometry(QtCore.QRect(130, 65, 560, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.NodeField.setFont(font)
        self.NodeField.setObjectName(_fromUtf8("NodeField"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 65, 80, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_16 = QtGui.QLabel(ConnectingCentroids)
        self.label_16.setGeometry(QtCore.QRect(270, 510, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_15 = QtGui.QLabel(ConnectingCentroids)
        self.label_15.setGeometry(QtCore.QRect(10, 512, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.progress_label = QtGui.QLabel(ConnectingCentroids)
        self.progress_label.setGeometry(QtCore.QRect(230, 471, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName(_fromUtf8("progress_label"))

        self.retranslateUi(ConnectingCentroids)
        QtCore.QMetaObject.connectSlotsByName(ConnectingCentroids)

    def retranslateUi(self, ConnectingCentroids):
        ConnectingCentroids.setWindowTitle(_translate("ConnectingCentroids", "AequilibraE -Centroid connection toolbox", None))
        self.groupBox.setTitle(_translate("ConnectingCentroids", "Centroids layer", None))
        self.label_3.setText(_translate("ConnectingCentroids", "Connectors per centroid", None))
        self.MaxLength.setText(_translate("ConnectingCentroids", "50000", None))
        self.label_2.setText(_translate("ConnectingCentroids", "Centroid layer", None))
        self.label_5.setText(_translate("ConnectingCentroids", "ID field", None))
        self.IfMaxLength.setText(_translate("ConnectingCentroids", "Connector Maximum length", None))
        self.label_6.setText(_translate("ConnectingCentroids", "meters", None))
        self.groupBox_2.setTitle(_translate("ConnectingCentroids", "Links layer", None))
        self.label.setText(_translate("ConnectingCentroids", "Network Layer", None))
        self.ChooseLineLayer.setText(_translate("ConnectingCentroids", "New line layer", None))
        self.pushOK.setText(_translate("ConnectingCentroids", "Run!", None))
        self.pushClose.setText(_translate("ConnectingCentroids", "Close", None))
        self.groupBox_3.setTitle(_translate("ConnectingCentroids", "Nodes Layer", None))
        self.label_4.setText(_translate("ConnectingCentroids", "Node Layer", None))
        self.ChooseNodeLayer.setText(_translate("ConnectingCentroids", "New node layer", None))
        self.SelectedNodes.setText(_translate("ConnectingCentroids", "Use only selected nodes", None))
        self.label_7.setText(_translate("ConnectingCentroids", "ID field", None))
        self.label_16.setText(_translate("ConnectingCentroids", " www.ipea.gov.br", None))
        self.label_15.setText(_translate("ConnectingCentroids", "The development of this tool was partially funded by:", None))
        self.progress_label.setText(_translate("ConnectingCentroids", "...", None))

