# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Create_Graph.ui'
#
# Created: Thu Jul 21 11:32:26 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Create_Graph(object):
    def setupUi(self, Create_Graph):
        Create_Graph.setObjectName(_fromUtf8("Create_Graph"))
        Create_Graph.setWindowModality(QtCore.Qt.NonModal)
        Create_Graph.resize(561, 370)
        Create_Graph.setModal(False)
        self.Tabs = QtGui.QTabWidget(Create_Graph)
        self.Tabs.setGeometry(QtCore.QRect(10, 10, 541, 311))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Tabs.setFont(font)
        self.Tabs.setObjectName(_fromUtf8("Tabs"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lblnodematch_11 = QtGui.QLabel(self.tab_2)
        self.lblnodematch_11.setGeometry(QtCore.QRect(50, 27, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_11.setFont(font)
        self.lblnodematch_11.setObjectName(_fromUtf8("lblnodematch_11"))
        self.network_layer = QtGui.QComboBox(self.tab_2)
        self.network_layer.setGeometry(QtCore.QRect(120, 27, 401, 22))
        self.network_layer.setMaxVisibleItems(10)
        self.network_layer.setObjectName(_fromUtf8("network_layer"))
        self.links_are_bi_directional = QtGui.QCheckBox(self.tab_2)
        self.links_are_bi_directional.setGeometry(QtCore.QRect(330, 60, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.links_are_bi_directional.setFont(font)
        self.links_are_bi_directional.setChecked(True)
        self.links_are_bi_directional.setObjectName(_fromUtf8("links_are_bi_directional"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(100, 133, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ba_length = QtGui.QComboBox(self.tab_2)
        self.ba_length.setGeometry(QtCore.QRect(190, 200, 331, 22))
        self.ba_length.setObjectName(_fromUtf8("ba_length"))
        self.direction_field = QtGui.QComboBox(self.tab_2)
        self.direction_field.setGeometry(QtCore.QRect(190, 167, 331, 22))
        self.direction_field.setObjectName(_fromUtf8("direction_field"))
        self.dir_label = QtGui.QLabel(self.tab_2)
        self.dir_label.setGeometry(QtCore.QRect(99, 171, 81, 16))
        self.dir_label.setObjectName(_fromUtf8("dir_label"))
        self.ab_length = QtGui.QComboBox(self.tab_2)
        self.ab_length.setGeometry(QtCore.QRect(190, 130, 331, 22))
        self.ab_length.setObjectName(_fromUtf8("ab_length"))
        self.ba_length_lbl = QtGui.QLabel(self.tab_2)
        self.ba_length_lbl.setGeometry(QtCore.QRect(100, 203, 71, 16))
        self.ba_length_lbl.setObjectName(_fromUtf8("ba_length_lbl"))
        self.use_link_selection = QtGui.QCheckBox(self.tab_2)
        self.use_link_selection.setGeometry(QtCore.QRect(130, 60, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_link_selection.setFont(font)
        self.use_link_selection.setObjectName(_fromUtf8("use_link_selection"))
        self.link_id = QtGui.QComboBox(self.tab_2)
        self.link_id.setGeometry(QtCore.QRect(190, 90, 331, 22))
        self.link_id.setObjectName(_fromUtf8("link_id"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(101, 93, 41, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.model_centroids = QtGui.QLineEdit(self.tab_2)
        self.model_centroids.setEnabled(False)
        self.model_centroids.setGeometry(QtCore.QRect(480, 260, 41, 20))
        self.model_centroids.setText(_fromUtf8(""))
        self.model_centroids.setObjectName(_fromUtf8("model_centroids"))
        self.set_centroids_rule = QtGui.QCheckBox(self.tab_2)
        self.set_centroids_rule.setGeometry(QtCore.QRect(280, 260, 211, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.set_centroids_rule.setFont(font)
        self.set_centroids_rule.setObjectName(_fromUtf8("set_centroids_rule"))
        self.path_through_connectors = QtGui.QCheckBox(self.tab_2)
        self.path_through_connectors.setGeometry(QtCore.QRect(10, 260, 231, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.path_through_connectors.setFont(font)
        self.path_through_connectors.setObjectName(_fromUtf8("path_through_connectors"))
        self.Tabs.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.skim_list = QtGui.QTableWidget(self.tab_4)
        self.skim_list.setGeometry(QtCore.QRect(33, 80, 471, 201))
        self.skim_list.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.skim_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.skim_list.setRowCount(0)
        self.skim_list.setColumnCount(3)
        self.skim_list.setObjectName(_fromUtf8("skim_list"))
        item = QtGui.QTableWidgetItem()
        self.skim_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.skim_list.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.skim_list.setHorizontalHeaderItem(2, item)
        self.skim_list.verticalHeader().setDefaultSectionSize(27)
        self.add_skim = QtGui.QPushButton(self.tab_4)
        self.add_skim.setGeometry(QtCore.QRect(33, 20, 91, 51))
        self.add_skim.setObjectName(_fromUtf8("add_skim"))
        self.ab_skim = QtGui.QComboBox(self.tab_4)
        self.ab_skim.setGeometry(QtCore.QRect(203, 20, 301, 22))
        self.ab_skim.setObjectName(_fromUtf8("ab_skim"))
        self.ba_skim = QtGui.QComboBox(self.tab_4)
        self.ba_skim.setGeometry(QtCore.QRect(203, 50, 301, 22))
        self.ba_skim.setObjectName(_fromUtf8("ba_skim"))
        self.lblnodematch_12 = QtGui.QLabel(self.tab_4)
        self.lblnodematch_12.setGeometry(QtCore.QRect(140, 23, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_12.setFont(font)
        self.lblnodematch_12.setObjectName(_fromUtf8("lblnodematch_12"))
        self.lblnodematch_13 = QtGui.QLabel(self.tab_4)
        self.lblnodematch_13.setGeometry(QtCore.QRect(141, 53, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_13.setFont(font)
        self.lblnodematch_13.setObjectName(_fromUtf8("lblnodematch_13"))
        self.Tabs.addTab(self.tab_4, _fromUtf8(""))
        self.StatusPage = QtGui.QWidget()
        self.StatusPage.setObjectName(_fromUtf8("StatusPage"))
        self.create_network = QtGui.QPushButton(self.StatusPage)
        self.create_network.setGeometry(QtCore.QRect(413, 250, 111, 31))
        self.create_network.setObjectName(_fromUtf8("create_network"))
        self.cancel = QtGui.QPushButton(self.StatusPage)
        self.cancel.setGeometry(QtCore.QRect(293, 250, 111, 31))
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.select_result = QtGui.QPushButton(self.StatusPage)
        self.select_result.setGeometry(QtCore.QRect(20, 20, 121, 23))
        self.select_result.setObjectName(_fromUtf8("select_result"))
        self.graph_file = QtGui.QLineEdit(self.StatusPage)
        self.graph_file.setGeometry(QtCore.QRect(160, 20, 331, 20))
        self.graph_file.setObjectName(_fromUtf8("graph_file"))
        self.Tabs.addTab(self.StatusPage, _fromUtf8(""))
        self.lbl_funding2 = QtGui.QLabel(Create_Graph)
        self.lbl_funding2.setGeometry(QtCore.QRect(460, 340, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_funding2.setFont(font)
        self.lbl_funding2.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_funding2.setObjectName(_fromUtf8("lbl_funding2"))
        self.lbl_funding1 = QtGui.QLabel(Create_Graph)
        self.lbl_funding1.setGeometry(QtCore.QRect(380, 343, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lbl_funding1.setFont(font)
        self.lbl_funding1.setObjectName(_fromUtf8("lbl_funding1"))
        self.progressbar0 = QtGui.QProgressBar(Create_Graph)
        self.progressbar0.setEnabled(True)
        self.progressbar0.setGeometry(QtCore.QRect(11, 336, 231, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar0.setPalette(palette)
        self.progressbar0.setProperty("value", 0)
        self.progressbar0.setTextVisible(True)
        self.progressbar0.setObjectName(_fromUtf8("progressbar0"))
        self.progress_label0 = QtGui.QLabel(Create_Graph)
        self.progress_label0.setGeometry(QtCore.QRect(252, 338, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label0.setFont(font)
        self.progress_label0.setObjectName(_fromUtf8("progress_label0"))

        self.retranslateUi(Create_Graph)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Create_Graph)

    def retranslateUi(self, Create_Graph):
        Create_Graph.setWindowTitle(_translate("Create_Graph", "Graph creation toolbox - Provided by www.xl-optim.com", None))
        self.lblnodematch_11.setText(_translate("Create_Graph", "Link layer", None))
        self.links_are_bi_directional.setText(_translate("Create_Graph", "Bi-directional links", None))
        self.label_5.setText(_translate("Create_Graph", "Length AB", None))
        self.dir_label.setText(_translate("Create_Graph", "Direction Field", None))
        self.ba_length_lbl.setText(_translate("Create_Graph", "Length BA", None))
        self.use_link_selection.setText(_translate("Create_Graph", "Use selected links only", None))
        self.label_8.setText(_translate("Create_Graph", "Link ID", None))
        self.set_centroids_rule.setText(_translate("Create_Graph", "Define number of centroids", None))
        self.path_through_connectors.setText(_translate("Create_Graph", "Block path through connectors", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("Create_Graph", "Network", None))
        self.skim_list.setAccessibleName(_translate("Create_Graph", "<html><head/><body><p>xcxc</p></body></html>", None))
        item = self.skim_list.horizontalHeaderItem(0)
        item.setText(_translate("Create_Graph", "Field name", None))
        item = self.skim_list.horizontalHeaderItem(1)
        item.setText(_translate("Create_Graph", "AB Field", None))
        item = self.skim_list.horizontalHeaderItem(2)
        item.setText(_translate("Create_Graph", "BA_Field", None))
        self.add_skim.setText(_translate("Create_Graph", "Add link field", None))
        self.lblnodematch_12.setText(_translate("Create_Graph", "AB Field", None))
        self.lblnodematch_13.setText(_translate("Create_Graph", "BA Field", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_4), _translate("Create_Graph", "Skims", None))
        self.create_network.setText(_translate("Create_Graph", "Create graph", None))
        self.cancel.setText(_translate("Create_Graph", "Cancel", None))
        self.select_result.setText(_translate("Create_Graph", "Network file", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.StatusPage), _translate("Create_Graph", "Create network", None))
        self.lbl_funding2.setText(_translate("Create_Graph", " www.ipea.gov.br", None))
        self.lbl_funding1.setText(_translate("Create_Graph", "Partially funded by", None))
        self.progress_label0.setText(_translate("Create_Graph", "Status Message 0", None))

