# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gravity_calibration.ui'
#
# Created: Wed Aug 17 19:01:53 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_gravity_calibration(object):
    def setupUi(self, gravity_calibration):
        gravity_calibration.setObjectName(_fromUtf8("gravity_calibration"))
        gravity_calibration.setWindowModality(QtCore.Qt.ApplicationModal)
        gravity_calibration.resize(716, 302)
        font = QtGui.QFont()
        font.setPointSize(9)
        gravity_calibration.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gravity_calibration.setWindowIcon(icon)
        gravity_calibration.setModal(True)
        self.but_calibrate_gravity = QtGui.QPushButton(gravity_calibration)
        self.but_calibrate_gravity.setGeometry(QtCore.QRect(10, 233, 691, 23))
        self.but_calibrate_gravity.setObjectName(_fromUtf8("but_calibrate_gravity"))
        self.groupBox = QtGui.QGroupBox(gravity_calibration)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 341, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.calib_friction = QtGui.QRadioButton(self.groupBox)
        self.calib_friction.setEnabled(False)
        self.calib_friction.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.calib_friction.setObjectName(_fromUtf8("calib_friction"))
        self.calib_gravity = QtGui.QRadioButton(self.groupBox)
        self.calib_gravity.setGeometry(QtCore.QRect(180, 20, 141, 17))
        self.calib_gravity.setChecked(True)
        self.calib_gravity.setObjectName(_fromUtf8("calib_gravity"))
        self.groupBox_5 = QtGui.QGroupBox(gravity_calibration)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 140, 341, 51))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.expo = QtGui.QRadioButton(self.groupBox_5)
        self.expo.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.expo.setChecked(True)
        self.expo.setObjectName(_fromUtf8("expo"))
        self.power = QtGui.QRadioButton(self.groupBox_5)
        self.power.setGeometry(QtCore.QRect(150, 20, 61, 17))
        self.power.setObjectName(_fromUtf8("power"))
        self.gamma = QtGui.QRadioButton(self.groupBox_5)
        self.gamma.setEnabled(False)
        self.gamma.setGeometry(QtCore.QRect(250, 20, 71, 17))
        self.gamma.setObjectName(_fromUtf8("gamma"))
        self.find_calibrate_gravity_result = QtGui.QPushButton(gravity_calibration)
        self.find_calibrate_gravity_result.setGeometry(QtCore.QRect(10, 200, 81, 23))
        self.find_calibrate_gravity_result.setObjectName(_fromUtf8("find_calibrate_gravity_result"))
        self.calibrate_gravity_result = QtGui.QLineEdit(gravity_calibration)
        self.calibrate_gravity_result.setGeometry(QtCore.QRect(100, 202, 561, 20))
        self.calibrate_gravity_result.setObjectName(_fromUtf8("calibrate_gravity_result"))
        self.progress_label = QtGui.QLabel(gravity_calibration)
        self.progress_label.setGeometry(QtCore.QRect(460, 268, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName(_fromUtf8("progress_label"))
        self.progressbar = QtGui.QProgressBar(gravity_calibration)
        self.progressbar.setEnabled(True)
        self.progressbar.setGeometry(QtCore.QRect(90, 268, 361, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar.setPalette(palette)
        self.progressbar.setProperty("value", 0)
        self.progressbar.setTextVisible(True)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))
        self.input_group = QtGui.QGroupBox(gravity_calibration)
        self.input_group.setGeometry(QtCore.QRect(10, 10, 341, 111))
        self.input_group.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.input_group.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.input_group.setFont(font)
        self.input_group.setObjectName(_fromUtf8("input_group"))
        self.input_numpy = QtGui.QRadioButton(self.input_group)
        self.input_numpy.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.input_numpy.setChecked(False)
        self.input_numpy.setObjectName(_fromUtf8("input_numpy"))
        self.input_omx = QtGui.QRadioButton(self.input_group)
        self.input_omx.setGeometry(QtCore.QRect(130, 30, 51, 17))
        self.input_omx.setChecked(True)
        self.input_omx.setObjectName(_fromUtf8("input_omx"))
        self.input_layer = QtGui.QRadioButton(self.input_group)
        self.input_layer.setGeometry(QtCore.QRect(220, 30, 81, 17))
        self.input_layer.setChecked(False)
        self.input_layer.setObjectName(_fromUtf8("input_layer"))
        self.but_load_input_matrix = QtGui.QPushButton(self.input_group)
        self.but_load_input_matrix.setGeometry(QtCore.QRect(20, 70, 81, 23))
        self.but_load_input_matrix.setObjectName(_fromUtf8("but_load_input_matrix"))
        self.label_loaded_input = QtGui.QLabel(self.input_group)
        self.label_loaded_input.setGeometry(QtCore.QRect(150, 70, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wingdings 2"))
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_loaded_input.setFont(font)
        self.label_loaded_input.setObjectName(_fromUtf8("label_loaded_input"))
        self.but_view_input_matrix = QtGui.QPushButton(self.input_group)
        self.but_view_input_matrix.setGeometry(QtCore.QRect(230, 70, 81, 23))
        self.but_view_input_matrix.setObjectName(_fromUtf8("but_view_input_matrix"))
        self.impedance_group = QtGui.QGroupBox(gravity_calibration)
        self.impedance_group.setGeometry(QtCore.QRect(360, 10, 341, 111))
        self.impedance_group.setObjectName(_fromUtf8("impedance_group"))
        self.impedance_numpy = QtGui.QRadioButton(self.impedance_group)
        self.impedance_numpy.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.impedance_numpy.setChecked(False)
        self.impedance_numpy.setObjectName(_fromUtf8("impedance_numpy"))
        self.impedance_omx = QtGui.QRadioButton(self.impedance_group)
        self.impedance_omx.setGeometry(QtCore.QRect(130, 30, 51, 17))
        self.impedance_omx.setChecked(True)
        self.impedance_omx.setObjectName(_fromUtf8("impedance_omx"))
        self.impedance_layer = QtGui.QRadioButton(self.impedance_group)
        self.impedance_layer.setGeometry(QtCore.QRect(220, 30, 81, 17))
        self.impedance_layer.setChecked(False)
        self.impedance_layer.setObjectName(_fromUtf8("impedance_layer"))
        self.but_load_impedance_matrix = QtGui.QPushButton(self.impedance_group)
        self.but_load_impedance_matrix.setGeometry(QtCore.QRect(20, 70, 81, 23))
        self.but_load_impedance_matrix.setObjectName(_fromUtf8("but_load_impedance_matrix"))
        self.label_loaded_impedance = QtGui.QLabel(self.impedance_group)
        self.label_loaded_impedance.setGeometry(QtCore.QRect(150, 70, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wingdings 2"))
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_loaded_impedance.setFont(font)
        self.label_loaded_impedance.setObjectName(_fromUtf8("label_loaded_impedance"))
        self.but_view_impedance_matrix = QtGui.QPushButton(self.impedance_group)
        self.but_view_impedance_matrix.setGeometry(QtCore.QRect(230, 70, 81, 23))
        self.but_view_impedance_matrix.setObjectName(_fromUtf8("but_view_impedance_matrix"))

        self.retranslateUi(gravity_calibration)
        QtCore.QMetaObject.connectSlotsByName(gravity_calibration)

    def retranslateUi(self, gravity_calibration):
        gravity_calibration.setWindowTitle(_translate("gravity_calibration", "AequilibraE  -  Gravity calibration", None))
        self.but_calibrate_gravity.setText(_translate("gravity_calibration", "CALIBRATE", None))
        self.groupBox.setTitle(_translate("gravity_calibration", "Model Type", None))
        self.calib_friction.setText(_translate("gravity_calibration", "Friction Factors", None))
        self.calib_gravity.setText(_translate("gravity_calibration", "Synthetic gravity", None))
        self.groupBox_5.setTitle(_translate("gravity_calibration", "Deterrence Function", None))
        self.expo.setText(_translate("gravity_calibration", "Exponential", None))
        self.power.setText(_translate("gravity_calibration", "Power", None))
        self.gamma.setText(_translate("gravity_calibration", "Gamma", None))
        self.find_calibrate_gravity_result.setText(_translate("gravity_calibration", "Result File", None))
        self.progress_label.setText(_translate("gravity_calibration", "Status Message 1", None))
        self.input_group.setTitle(_translate("gravity_calibration", "Input Matrix", None))
        self.input_numpy.setText(_translate("gravity_calibration", "Numpy array", None))
        self.input_omx.setText(_translate("gravity_calibration", "OMX", None))
        self.input_layer.setText(_translate("gravity_calibration", "Layer-style", None))
        self.but_load_input_matrix.setText(_translate("gravity_calibration", "Load Matrix", None))
        self.label_loaded_input.setText(_translate("gravity_calibration", "O", None))
        self.but_view_input_matrix.setText(_translate("gravity_calibration", "View", None))
        self.impedance_group.setTitle(_translate("gravity_calibration", "Impedance matrix", None))
        self.impedance_numpy.setText(_translate("gravity_calibration", "Numpy array", None))
        self.impedance_omx.setText(_translate("gravity_calibration", "OMX", None))
        self.impedance_layer.setText(_translate("gravity_calibration", "Layer-style", None))
        self.but_load_impedance_matrix.setText(_translate("gravity_calibration", "Load Matrix", None))
        self.label_loaded_impedance.setText(_translate("gravity_calibration", "O", None))
        self.but_view_impedance_matrix.setText(_translate("gravity_calibration", "View", None))

