# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ipf.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ipf(object):
    def setupUi(self, ipf):
        ipf.setObjectName(_fromUtf8("ipf"))
        ipf.setWindowModality(QtCore.Qt.ApplicationModal)
        ipf.resize(546, 196)
        ipf.setModal(True)
        self.lbl_funding2 = QtGui.QLabel(ipf)
        self.lbl_funding2.setGeometry(QtCore.QRect(448, 163, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_funding2.setFont(font)
        self.lbl_funding2.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_funding2.setObjectName(_fromUtf8("lbl_funding2"))
        self.lbl_funding1 = QtGui.QLabel(ipf)
        self.lbl_funding1.setGeometry(QtCore.QRect(360, 164, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lbl_funding1.setFont(font)
        self.lbl_funding1.setObjectName(_fromUtf8("lbl_funding1"))
        self.progressbar = QtGui.QProgressBar(ipf)
        self.progressbar.setEnabled(True)
        self.progressbar.setGeometry(QtCore.QRect(10, 161, 251, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar.setPalette(palette)
        self.progressbar.setProperty("value", 0)
        self.progressbar.setTextVisible(True)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))
        self.progress_label = QtGui.QLabel(ipf)
        self.progress_label.setGeometry(QtCore.QRect(270, 163, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName(_fromUtf8("progress_label"))
        self.but_load_new_matrix = QtGui.QPushButton(ipf)
        self.but_load_new_matrix.setGeometry(QtCore.QRect(10, 10, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_new_matrix.setFont(font)
        self.but_load_new_matrix.setObjectName(_fromUtf8("but_load_new_matrix"))
        self.apply_ipf = QtGui.QPushButton(ipf)
        self.apply_ipf.setGeometry(QtCore.QRect(10, 160, 140, 25))
        self.apply_ipf.setObjectName(_fromUtf8("apply_ipf"))
        self.matrix_name = QtGui.QLabel(ipf)
        self.matrix_name.setGeometry(QtCore.QRect(12, 40, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.matrix_name.setFont(font)
        self.matrix_name.setObjectName(_fromUtf8("matrix_name"))
        self.matrix_total = QtGui.QLabel(ipf)
        self.matrix_total.setGeometry(QtCore.QRect(12, 62, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.matrix_total.setFont(font)
        self.matrix_total.setText(_fromUtf8(""))
        self.matrix_total.setObjectName(_fromUtf8("matrix_total"))
        self.but_load_rows = QtGui.QPushButton(ipf)
        self.but_load_rows.setGeometry(QtCore.QRect(200, 10, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_rows.setFont(font)
        self.but_load_rows.setObjectName(_fromUtf8("but_load_rows"))
        self.but_load_columns = QtGui.QPushButton(ipf)
        self.but_load_columns.setGeometry(QtCore.QRect(385, 10, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_columns.setFont(font)
        self.but_load_columns.setObjectName(_fromUtf8("but_load_columns"))
        self.columns_name = QtGui.QLabel(ipf)
        self.columns_name.setGeometry(QtCore.QRect(387, 40, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.columns_name.setFont(font)
        self.columns_name.setObjectName(_fromUtf8("columns_name"))
        self.columns_total = QtGui.QLabel(ipf)
        self.columns_total.setGeometry(QtCore.QRect(387, 62, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.columns_total.setFont(font)
        self.columns_total.setText(_fromUtf8(""))
        self.columns_total.setObjectName(_fromUtf8("columns_total"))
        self.rows_total = QtGui.QLabel(ipf)
        self.rows_total.setGeometry(QtCore.QRect(202, 62, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rows_total.setFont(font)
        self.rows_total.setText(_fromUtf8(""))
        self.rows_total.setObjectName(_fromUtf8("rows_total"))
        self.rows_name = QtGui.QLabel(ipf)
        self.rows_name.setGeometry(QtCore.QRect(202, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rows_name.setFont(font)
        self.rows_name.setObjectName(_fromUtf8("rows_name"))
        self.but_choose_output_name = QtGui.QPushButton(ipf)
        self.but_choose_output_name.setGeometry(QtCore.QRect(10, 100, 140, 25))
        self.but_choose_output_name.setObjectName(_fromUtf8("but_choose_output_name"))
        self.output_name = QtGui.QLabel(ipf)
        self.output_name.setGeometry(QtCore.QRect(160, 102, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.output_name.setFont(font)
        self.output_name.setText(_fromUtf8(""))
        self.output_name.setObjectName(_fromUtf8("output_name"))
        self.progress_label.raise_()
        self.lbl_funding2.raise_()
        self.lbl_funding1.raise_()
        self.progressbar.raise_()
        self.but_load_new_matrix.raise_()
        self.apply_ipf.raise_()
        self.matrix_name.raise_()
        self.matrix_total.raise_()
        self.but_load_rows.raise_()
        self.but_load_columns.raise_()
        self.columns_name.raise_()
        self.columns_total.raise_()
        self.rows_total.raise_()
        self.rows_name.raise_()
        self.but_choose_output_name.raise_()
        self.output_name.raise_()

        self.retranslateUi(ipf)
        QtCore.QMetaObject.connectSlotsByName(ipf)

    def retranslateUi(self, ipf):
        ipf.setWindowTitle(_translate("ipf", "Aequilibrae - Iterative Proportional Fitting", None))
        self.lbl_funding2.setText(_translate("ipf", " www.ipea.gov.br", None))
        self.lbl_funding1.setText(_translate("ipf", "Partially funded by", None))
        self.progress_label.setText(_translate("ipf", "Status Message 0", None))
        self.but_load_new_matrix.setText(_translate("ipf", "Load seed matrix", None))
        self.apply_ipf.setText(_translate("ipf", "Run IPF", None))
        self.matrix_name.setText(_translate("ipf", "No matrix loaded", None))
        self.but_load_rows.setText(_translate("ipf", "Load zones vector", None))
        self.but_load_columns.setText(_translate("ipf", "Load columns vector", None))
        self.columns_name.setText(_translate("ipf", "No vector loaded", None))
        self.rows_name.setText(_translate("ipf", "No vector loaded", None))
        self.but_choose_output_name.setText(_translate("ipf", "Save Output", None))

