# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_impedance_matrix.ui'
#
# Created: Sun Oct 23 20:27:13 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Impedance_Matrix(object):
    def setupUi(self, Impedance_Matrix):
        Impedance_Matrix.setObjectName(_fromUtf8("Impedance_Matrix"))
        Impedance_Matrix.setWindowModality(QtCore.Qt.ApplicationModal)
        Impedance_Matrix.resize(627, 401)
        Impedance_Matrix.setModal(True)
        self.funding1 = QtGui.QLabel(Impedance_Matrix)
        self.funding1.setGeometry(QtCore.QRect(200, 371, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.funding1.setFont(font)
        self.funding1.setObjectName(_fromUtf8("funding1"))
        self.funding2 = QtGui.QLabel(Impedance_Matrix)
        self.funding2.setGeometry(QtCore.QRect(497, 369, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.funding2.setFont(font)
        self.funding2.setTextFormat(QtCore.Qt.PlainText)
        self.funding2.setObjectName(_fromUtf8("funding2"))
        self.groupBox = QtGui.QGroupBox(Impedance_Matrix)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 591, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.load_graph_from_file = QtGui.QPushButton(self.groupBox)
        self.load_graph_from_file.setGeometry(QtCore.QRect(10, 23, 121, 23))
        self.load_graph_from_file.setObjectName(_fromUtf8("load_graph_from_file"))
        self.graph_file_name = QtGui.QLineEdit(self.groupBox)
        self.graph_file_name.setGeometry(QtCore.QRect(150, 23, 431, 24))
        self.graph_file_name.setObjectName(_fromUtf8("graph_file_name"))
        self.cb_minimizing = QtGui.QComboBox(self.groupBox)
        self.cb_minimizing.setGeometry(QtCore.QRect(120, 53, 121, 24))
        self.cb_minimizing.setObjectName(_fromUtf8("cb_minimizing"))
        self.progress_label_2 = QtGui.QLabel(self.groupBox)
        self.progress_label_2.setGeometry(QtCore.QRect(20, 56, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label_2.setFont(font)
        self.progress_label_2.setObjectName(_fromUtf8("progress_label_2"))
        self.progress_label_3 = QtGui.QLabel(self.groupBox)
        self.progress_label_3.setGeometry(QtCore.QRect(260, 56, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label_3.setFont(font)
        self.progress_label_3.setObjectName(_fromUtf8("progress_label_3"))
        self.all_centroids = QtGui.QLineEdit(self.groupBox)
        self.all_centroids.setGeometry(QtCore.QRect(320, 56, 51, 20))
        self.all_centroids.setObjectName(_fromUtf8("all_centroids"))
        self.block_paths = QtGui.QCheckBox(self.groupBox)
        self.block_paths.setGeometry(QtCore.QRect(390, 56, 191, 20))
        self.block_paths.setObjectName(_fromUtf8("block_paths"))
        self.groupBox_3 = QtGui.QGroupBox(Impedance_Matrix)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 300, 591, 61))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.do_dist_matrix = QtGui.QPushButton(self.groupBox_3)
        self.do_dist_matrix.setGeometry(QtCore.QRect(503, 20, 81, 23))
        self.do_dist_matrix.setObjectName(_fromUtf8("do_dist_matrix"))
        self.select_result = QtGui.QPushButton(self.groupBox_3)
        self.select_result.setGeometry(QtCore.QRect(10, 20, 121, 23))
        self.select_result.setObjectName(_fromUtf8("select_result"))
        self.imped_results = QtGui.QLineEdit(self.groupBox_3)
        self.imped_results.setGeometry(QtCore.QRect(140, 20, 221, 24))
        self.imped_results.setObjectName(_fromUtf8("imped_results"))
        self.csv_res = QtGui.QRadioButton(self.groupBox_3)
        self.csv_res.setGeometry(QtCore.QRect(374, 22, 51, 17))
        self.csv_res.setChecked(True)
        self.csv_res.setObjectName(_fromUtf8("csv_res"))
        self.npy_res = QtGui.QRadioButton(self.groupBox_3)
        self.npy_res.setGeometry(QtCore.QRect(424, 22, 71, 17))
        self.npy_res.setObjectName(_fromUtf8("npy_res"))
        self.groupBox_2 = QtGui.QGroupBox(Impedance_Matrix)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 109, 591, 181))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.bt_add_skim = QtGui.QPushButton(self.groupBox_2)
        self.bt_add_skim.setGeometry(QtCore.QRect(10, 22, 121, 21))
        self.bt_add_skim.setObjectName(_fromUtf8("bt_add_skim"))
        self.skim_list = QtGui.QTableWidget(self.groupBox_2)
        self.skim_list.setGeometry(QtCore.QRect(10, 60, 571, 111))
        self.skim_list.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.skim_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.skim_list.setRowCount(0)
        self.skim_list.setColumnCount(1)
        self.skim_list.setObjectName(_fromUtf8("skim_list"))
        item = QtGui.QTableWidgetItem()
        self.skim_list.setHorizontalHeaderItem(0, item)
        self.skim_list.verticalHeader().setDefaultSectionSize(27)
        self.cb_skims = QtGui.QComboBox(self.groupBox_2)
        self.cb_skims.setGeometry(QtCore.QRect(170, 20, 401, 24))
        self.cb_skims.setObjectName(_fromUtf8("cb_skims"))
        self.progress_label = QtGui.QLabel(Impedance_Matrix)
        self.progress_label.setGeometry(QtCore.QRect(370, 370, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName(_fromUtf8("progress_label"))
        self.progressbar = QtGui.QProgressBar(Impedance_Matrix)
        self.progressbar.setEnabled(True)
        self.progressbar.setGeometry(QtCore.QRect(20, 370, 331, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar.setPalette(palette)
        self.progressbar.setProperty("value", 0)
        self.progressbar.setTextVisible(True)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))

        self.retranslateUi(Impedance_Matrix)
        QtCore.QMetaObject.connectSlotsByName(Impedance_Matrix)

    def retranslateUi(self, Impedance_Matrix):
        Impedance_Matrix.setWindowTitle(_translate("Impedance_Matrix", "Impedance matrix toolbox - Provided by www.xl-optim.com", None))
        self.funding1.setText(_translate("Impedance_Matrix", "The development of this tool was partially funded by:", None))
        self.funding2.setText(_translate("Impedance_Matrix", " www.ipea.gov.br", None))
        self.groupBox.setTitle(_translate("Impedance_Matrix", "GRAPH", None))
        self.load_graph_from_file.setText(_translate("Impedance_Matrix", "Load Graph file", None))
        self.progress_label_2.setText(_translate("Impedance_Matrix", "Minimize field:", None))
        self.progress_label_3.setText(_translate("Impedance_Matrix", "Centroids:", None))
        self.block_paths.setText(_translate("Impedance_Matrix", "Block path through centroids", None))
        self.groupBox_3.setTitle(_translate("Impedance_Matrix", "RESULTS", None))
        self.do_dist_matrix.setText(_translate("Impedance_Matrix", "Compute", None))
        self.select_result.setText(_translate("Impedance_Matrix", "Matrix results", None))
        self.csv_res.setText(_translate("Impedance_Matrix", "CSV", None))
        self.npy_res.setText(_translate("Impedance_Matrix", "NumPY", None))
        self.groupBox_2.setTitle(_translate("Impedance_Matrix", "SKIMS", None))
        self.bt_add_skim.setText(_translate("Impedance_Matrix", "Add Skim", None))
        self.skim_list.setAccessibleName(_translate("Impedance_Matrix", "<html><head/><body><p>xcxc</p></body></html>", None))
        item = self.skim_list.horizontalHeaderItem(0)
        item.setText(_translate("Impedance_Matrix", "Skims", None))
        self.progress_label.setText(_translate("Impedance_Matrix", "Status Message 0", None))

