# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_traffic_assignment.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from qgis.gui import QgsMapLayerComboBox

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_traffic_assignment(object):
    def setupUi(self, traffic_assignment):
        traffic_assignment.setObjectName(_fromUtf8("traffic_assignment"))
        traffic_assignment.setWindowModality(QtCore.Qt.ApplicationModal)
        traffic_assignment.resize(662, 411)
        traffic_assignment.setModal(True)
        self.tabWidget = QtGui.QTabWidget(traffic_assignment)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 641, 391))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.but_load_new_matrix = QtGui.QPushButton(self.widget)
        self.but_load_new_matrix.setGeometry(QtCore.QRect(20, 15, 261, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_new_matrix.setFont(font)
        self.but_load_new_matrix.setObjectName(_fromUtf8("but_load_new_matrix"))
        self.display_matrix = QtGui.QCheckBox(self.widget)
        self.display_matrix.setGeometry(QtCore.QRect(300, 20, 121, 17))
        self.display_matrix.setObjectName(_fromUtf8("display_matrix"))
        self.matrix_viewer = QtGui.QTableView(self.widget)
        self.matrix_viewer.setGeometry(QtCore.QRect(20, 50, 591, 291))
        self.matrix_viewer.setObjectName(_fromUtf8("matrix_viewer"))
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lblnodematch_11 = QtGui.QLabel(self.tab_2)
        self.lblnodematch_11.setGeometry(QtCore.QRect(50, 200, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_11.setFont(font)
        self.lblnodematch_11.setObjectName(_fromUtf8("lblnodematch_11"))
        self.minimizing_field = QtGui.QComboBox(self.tab_2)
        self.minimizing_field.setGeometry(QtCore.QRect(150, 72, 391, 24))
        self.minimizing_field.setObjectName(_fromUtf8("minimizing_field"))
        self.ba_time_lbl = QtGui.QLabel(self.tab_2)
        self.ba_time_lbl.setGeometry(QtCore.QRect(50, 75, 151, 16))
        self.ba_time_lbl.setObjectName(_fromUtf8("ba_time_lbl"))
        self.no_connectors_in_graph = QtGui.QCheckBox(self.tab_2)
        self.no_connectors_in_graph.setGeometry(QtCore.QRect(151, 100, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.no_connectors_in_graph.setFont(font)
        self.no_connectors_in_graph.setChecked(True)
        self.no_connectors_in_graph.setObjectName(_fromUtf8("no_connectors_in_graph"))
        self.load_graph_from_file = QtGui.QPushButton(self.tab_2)
        self.load_graph_from_file.setGeometry(QtCore.QRect(30, 30, 91, 23))
        self.load_graph_from_file.setObjectName(_fromUtf8("load_graph_from_file"))
        self.lbl_graphfile = QtGui.QLabel(self.tab_2)
        self.lbl_graphfile.setGeometry(QtCore.QRect(153, 35, 391, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_graphfile.setFont(font)
        self.lbl_graphfile.setObjectName(_fromUtf8("lbl_graphfile"))
        self.chb_check_consistency = QtGui.QCheckBox(self.tab_2)
        self.chb_check_consistency.setEnabled(False)
        self.chb_check_consistency.setGeometry(QtCore.QRect(410, 260, 131, 18))
        self.chb_check_consistency.setObjectName(_fromUtf8("chb_check_consistency"))
        self.lblnodematch_14 = QtGui.QLabel(self.tab_2)
        self.lblnodematch_14.setGeometry(QtCore.QRect(50, 230, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_14.setFont(font)
        self.lblnodematch_14.setObjectName(_fromUtf8("lblnodematch_14"))
        self.network_layer = QgsMapLayerComboBox(self.tab_2)
        self.network_layer.setGeometry(QtCore.QRect(151, 196, 391, 24))
        self.network_layer.setObjectName(_fromUtf8("network_layer"))
        self.network_field = QtGui.QComboBox(self.tab_2)
        self.network_field.setGeometry(QtCore.QRect(150, 230, 391, 24))
        self.network_field.setObjectName(_fromUtf8("network_field"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.skim_list = QtGui.QTableWidget(self.tab_4)
        self.skim_list.setGeometry(QtCore.QRect(20, 80, 261, 261))
        self.skim_list.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.skim_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.skim_list.setRowCount(0)
        self.skim_list.setColumnCount(1)
        self.skim_list.setObjectName(_fromUtf8("skim_list"))
        item = QtGui.QTableWidgetItem()
        self.skim_list.setHorizontalHeaderItem(0, item)
        self.skim_list.verticalHeader().setDefaultSectionSize(27)
        self.add_skim = QtGui.QPushButton(self.tab_4)
        self.add_skim.setGeometry(QtCore.QRect(20, 49, 261, 24))
        self.add_skim.setObjectName(_fromUtf8("add_skim"))
        self.skim_field = QtGui.QComboBox(self.tab_4)
        self.skim_field.setGeometry(QtCore.QRect(60, 20, 221, 24))
        self.skim_field.setObjectName(_fromUtf8("skim_field"))
        self.lblnodematch_12 = QtGui.QLabel(self.tab_4)
        self.lblnodematch_12.setGeometry(QtCore.QRect(25, 24, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_12.setFont(font)
        self.lblnodematch_12.setObjectName(_fromUtf8("lblnodematch_12"))
        self.select_link_analysis_4 = QtGui.QRadioButton(self.tab_4)
        self.select_link_analysis_4.setEnabled(False)
        self.select_link_analysis_4.setGeometry(QtCore.QRect(300, 92, 181, 17))
        self.select_link_analysis_4.setObjectName(_fromUtf8("select_link_analysis_4"))
        self.select_link_analysis = QtGui.QRadioButton(self.tab_4)
        self.select_link_analysis.setEnabled(False)
        self.select_link_analysis.setGeometry(QtCore.QRect(300, 60, 331, 17))
        self.select_link_analysis.setObjectName(_fromUtf8("select_link_analysis"))
        self.path_list = QtGui.QTableWidget(self.tab_4)
        self.path_list.setEnabled(False)
        self.path_list.setGeometry(QtCore.QRect(300, 122, 321, 211))
        self.path_list.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.path_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.path_list.setRowCount(0)
        self.path_list.setColumnCount(3)
        self.path_list.setObjectName(_fromUtf8("path_list"))
        item = QtGui.QTableWidgetItem()
        self.path_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.path_list.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.path_list.setHorizontalHeaderItem(2, item)
        self.path_list.verticalHeader().setDefaultSectionSize(27)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.do_assignment = QtGui.QPushButton(self.tab)
        self.do_assignment.setGeometry(QtCore.QRect(40, 106, 351, 23))
        self.do_assignment.setObjectName(_fromUtf8("do_assignment"))
        self.cancel_all = QtGui.QPushButton(self.tab)
        self.cancel_all.setGeometry(QtCore.QRect(410, 106, 131, 23))
        self.cancel_all.setObjectName(_fromUtf8("cancel_all"))
        self.select_result = QtGui.QPushButton(self.tab)
        self.select_result.setGeometry(QtCore.QRect(10, 60, 121, 24))
        self.select_result.setObjectName(_fromUtf8("select_result"))
        self.cb_choose_algorithm = QtGui.QComboBox(self.tab)
        self.cb_choose_algorithm.setGeometry(QtCore.QRect(80, 20, 531, 24))
        self.cb_choose_algorithm.setMaxVisibleItems(10)
        self.cb_choose_algorithm.setObjectName(_fromUtf8("cb_choose_algorithm"))
        self.lblnodematch_13 = QtGui.QLabel(self.tab)
        self.lblnodematch_13.setGeometry(QtCore.QRect(10, 24, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_13.setFont(font)
        self.lblnodematch_13.setObjectName(_fromUtf8("lblnodematch_13"))
        self.progress_label0 = QtGui.QLabel(self.tab)
        self.progress_label0.setGeometry(QtCore.QRect(250, 329, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label0.setFont(font)
        self.progress_label0.setObjectName(_fromUtf8("progress_label0"))
        self.progressbar0 = QtGui.QProgressBar(self.tab)
        self.progressbar0.setEnabled(True)
        self.progressbar0.setGeometry(QtCore.QRect(9, 327, 231, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar0.setPalette(palette)
        self.progressbar0.setProperty("value", 0)
        self.progressbar0.setTextVisible(True)
        self.progressbar0.setObjectName(_fromUtf8("progressbar0"))
        self.lbl_output = QtGui.QLabel(self.tab)
        self.lbl_output.setGeometry(QtCore.QRect(150, 61, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_output.setFont(font)
        self.lbl_output.setObjectName(_fromUtf8("lbl_output"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(traffic_assignment)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(traffic_assignment)

    def retranslateUi(self, traffic_assignment):
        traffic_assignment.setWindowTitle(_translate("traffic_assignment", "Traffic Assignment toolbox - Provided by www.xl-optim.com", None))
        self.but_load_new_matrix.setText(_translate("traffic_assignment", "Load new matrix", None))
        self.display_matrix.setText(_translate("traffic_assignment", "Display Matrix", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("traffic_assignment", "Demand", None))
        self.lblnodematch_11.setText(_translate("traffic_assignment", "Line layer", None))
        self.ba_time_lbl.setText(_translate("traffic_assignment", "Minimizing field", None))
        self.no_connectors_in_graph.setText(_translate("traffic_assignment", "Prevent flows through centroid connectors", None))
        self.load_graph_from_file.setText(_translate("traffic_assignment", "Load Graph", None))
        self.lbl_graphfile.setText(_translate("traffic_assignment", "Load graph *.aeg", None))
        self.chb_check_consistency.setText(_translate("traffic_assignment", "Check consistency", None))
        self.lblnodematch_14.setText(_translate("traffic_assignment", "Link ID field", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("traffic_assignment", "Network", None))
        self.skim_list.setAccessibleName(_translate("traffic_assignment", "<html><head/><body><p>xcxc</p></body></html>", None))
        item = self.skim_list.horizontalHeaderItem(0)
        item.setText(_translate("traffic_assignment", "Skim name", None))
        self.add_skim.setText(_translate("traffic_assignment", "Add Skim", None))
        self.lblnodematch_12.setText(_translate("traffic_assignment", "Field", None))
        self.select_link_analysis_4.setText(_translate("traffic_assignment", "Complete path file", None))
        self.select_link_analysis.setText(_translate("traffic_assignment", "Select link analysis", None))
        self.path_list.setAccessibleName(_translate("traffic_assignment", "<html><head/><body><p>xcxc</p></body></html>", None))
        item = self.path_list.horizontalHeaderItem(0)
        item.setText(_translate("traffic_assignment", "Query Type", None))
        item = self.path_list.horizontalHeaderItem(1)
        item.setText(_translate("traffic_assignment", "Query ID", None))
        item = self.path_list.horizontalHeaderItem(2)
        item.setText(_translate("traffic_assignment", "Querying element", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("traffic_assignment", "Skims", None))
        self.do_assignment.setText(_translate("traffic_assignment", "ASSIGN", None))
        self.cancel_all.setText(_translate("traffic_assignment", "CANCEL", None))
        self.select_result.setText(_translate("traffic_assignment", "Assignment results", None))
        self.lblnodematch_13.setText(_translate("traffic_assignment", "Algorithm", None))
        self.progress_label0.setText(_translate("traffic_assignment", "Status Message 0", None))
        self.lbl_output.setText(_translate("traffic_assignment", "Output", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("traffic_assignment", "Assignment", None))


