# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Trip_Distribution.ui'
#
# Created: Tue Oct 14 15:39:22 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_trip_distribution(object):
    def setupUi(self, trip_distribution):
        trip_distribution.setObjectName(_fromUtf8("trip_distribution"))
        trip_distribution.resize(808, 507)
        font = QtGui.QFont()
        font.setPointSize(9)
        trip_distribution.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        trip_distribution.setWindowIcon(icon)
        self.cancel = QtGui.QPushButton(trip_distribution)
        self.cancel.setGeometry(QtCore.QRect(40, 470, 721, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.cancel.setPalette(palette)
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.tabWidget = QtGui.QTabWidget(trip_distribution)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 771, 451))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.calibrate_gravity = QtGui.QPushButton(self.tab)
        self.calibrate_gravity.setGeometry(QtCore.QRect(20, 360, 681, 23))
        self.calibrate_gravity.setObjectName(_fromUtf8("calibrate_gravity"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 341, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.calib_friction = QtGui.QRadioButton(self.groupBox)
        self.calib_friction.setEnabled(False)
        self.calib_friction.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.calib_friction.setObjectName(_fromUtf8("calib_friction"))
        self.calib_gravity = QtGui.QRadioButton(self.groupBox)
        self.calib_gravity.setGeometry(QtCore.QRect(180, 20, 141, 17))
        self.calib_gravity.setChecked(True)
        self.calib_gravity.setObjectName(_fromUtf8("calib_gravity"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 120, 341, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.impedance_to_calib = QtGui.QComboBox(self.groupBox_3)
        self.impedance_to_calib.setEnabled(True)
        self.impedance_to_calib.setGeometry(QtCore.QRect(110, 80, 211, 22))
        self.impedance_to_calib.setMaxVisibleItems(10)
        self.impedance_to_calib.setObjectName(_fromUtf8("impedance_to_calib"))
        self.impedance_from_calib = QtGui.QComboBox(self.groupBox_3)
        self.impedance_from_calib.setGeometry(QtCore.QRect(110, 50, 211, 22))
        self.impedance_from_calib.setMaxVisibleItems(10)
        self.impedance_from_calib.setObjectName(_fromUtf8("impedance_from_calib"))
        self.lblareamatch = QtGui.QLabel(self.groupBox_3)
        self.lblareamatch.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.lblareamatch.setObjectName(_fromUtf8("lblareamatch"))
        self.lblnodematch = QtGui.QLabel(self.groupBox_3)
        self.lblnodematch.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.lblnodematch.setObjectName(_fromUtf8("lblnodematch"))
        self.impedance_layer_calib = QtGui.QComboBox(self.groupBox_3)
        self.impedance_layer_calib.setGeometry(QtCore.QRect(110, 20, 211, 22))
        self.impedance_layer_calib.setMaxVisibleItems(10)
        self.impedance_layer_calib.setObjectName(_fromUtf8("impedance_layer_calib"))
        self.impedance_cost_calib = QtGui.QComboBox(self.groupBox_3)
        self.impedance_cost_calib.setEnabled(True)
        self.impedance_cost_calib.setGeometry(QtCore.QRect(110, 110, 211, 22))
        self.impedance_cost_calib.setMaxVisibleItems(10)
        self.impedance_cost_calib.setObjectName(_fromUtf8("impedance_cost_calib"))
        self.lblareamatch_2 = QtGui.QLabel(self.groupBox_3)
        self.lblareamatch_2.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.lblareamatch_2.setObjectName(_fromUtf8("lblareamatch_2"))
        self.lblareamatch_3 = QtGui.QLabel(self.groupBox_3)
        self.lblareamatch_3.setGeometry(QtCore.QRect(10, 110, 121, 16))
        self.lblareamatch_3.setObjectName(_fromUtf8("lblareamatch_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(370, 30, 341, 51))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.expo = QtGui.QRadioButton(self.groupBox_5)
        self.expo.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.expo.setChecked(True)
        self.expo.setObjectName(_fromUtf8("expo"))
        self.power = QtGui.QRadioButton(self.groupBox_5)
        self.power.setGeometry(QtCore.QRect(150, 20, 61, 17))
        self.power.setObjectName(_fromUtf8("power"))
        self.gamma = QtGui.QRadioButton(self.groupBox_5)
        self.gamma.setEnabled(False)
        self.gamma.setGeometry(QtCore.QRect(250, 20, 71, 17))
        self.gamma.setObjectName(_fromUtf8("gamma"))
        self.groupBox_23 = QtGui.QGroupBox(self.tab)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 120, 341, 141))
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.inputmatrix_to = QtGui.QComboBox(self.groupBox_23)
        self.inputmatrix_to.setEnabled(True)
        self.inputmatrix_to.setGeometry(QtCore.QRect(110, 80, 211, 22))
        self.inputmatrix_to.setMaxVisibleItems(10)
        self.inputmatrix_to.setObjectName(_fromUtf8("inputmatrix_to"))
        self.inputmatrix_from = QtGui.QComboBox(self.groupBox_23)
        self.inputmatrix_from.setGeometry(QtCore.QRect(110, 50, 211, 22))
        self.inputmatrix_from.setMaxVisibleItems(10)
        self.inputmatrix_from.setObjectName(_fromUtf8("inputmatrix_from"))
        self.lblareamatch_19 = QtGui.QLabel(self.groupBox_23)
        self.lblareamatch_19.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.lblareamatch_19.setObjectName(_fromUtf8("lblareamatch_19"))
        self.lblnodematch_10 = QtGui.QLabel(self.groupBox_23)
        self.lblnodematch_10.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.lblnodematch_10.setObjectName(_fromUtf8("lblnodematch_10"))
        self.inputmatrix_calib = QtGui.QComboBox(self.groupBox_23)
        self.inputmatrix_calib.setGeometry(QtCore.QRect(110, 20, 211, 22))
        self.inputmatrix_calib.setMaxVisibleItems(10)
        self.inputmatrix_calib.setObjectName(_fromUtf8("inputmatrix_calib"))
        self.inputmatrix_flow = QtGui.QComboBox(self.groupBox_23)
        self.inputmatrix_flow.setEnabled(True)
        self.inputmatrix_flow.setGeometry(QtCore.QRect(110, 110, 211, 22))
        self.inputmatrix_flow.setMaxVisibleItems(10)
        self.inputmatrix_flow.setObjectName(_fromUtf8("inputmatrix_flow"))
        self.lblareamatch_20 = QtGui.QLabel(self.groupBox_23)
        self.lblareamatch_20.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.lblareamatch_20.setObjectName(_fromUtf8("lblareamatch_20"))
        self.lblareamatch_21 = QtGui.QLabel(self.groupBox_23)
        self.lblareamatch_21.setGeometry(QtCore.QRect(10, 110, 121, 16))
        self.lblareamatch_21.setObjectName(_fromUtf8("lblareamatch_21"))
        self.calibrate_gravity_result = QtGui.QLineEdit(self.tab)
        self.calibrate_gravity_result.setGeometry(QtCore.QRect(140, 310, 561, 20))
        self.calibrate_gravity_result.setObjectName(_fromUtf8("calibrate_gravity_result"))
        self.find_calibrate_gravity_result = QtGui.QPushButton(self.tab)
        self.find_calibrate_gravity_result.setGeometry(QtCore.QRect(20, 310, 81, 23))
        self.find_calibrate_gravity_result.setObjectName(_fromUtf8("find_calibrate_gravity_result"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.apply_gravity = QtGui.QPushButton(self.tab_3)
        self.apply_gravity.setGeometry(QtCore.QRect(50, 350, 691, 23))
        self.apply_gravity.setObjectName(_fromUtf8("apply_gravity"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(50, 20, 291, 51))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.apply_friction = QtGui.QRadioButton(self.groupBox_4)
        self.apply_friction.setEnabled(False)
        self.apply_friction.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.apply_friction.setObjectName(_fromUtf8("apply_friction"))
        self.apply_syntethic = QtGui.QRadioButton(self.groupBox_4)
        self.apply_syntethic.setGeometry(QtCore.QRect(170, 20, 141, 17))
        self.apply_syntethic.setChecked(True)
        self.apply_syntethic.setObjectName(_fromUtf8("apply_syntethic"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(450, 20, 291, 51))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.Apply_expo = QtGui.QRadioButton(self.groupBox_7)
        self.Apply_expo.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.Apply_expo.setChecked(True)
        self.Apply_expo.setObjectName(_fromUtf8("Apply_expo"))
        self.Apply_power = QtGui.QRadioButton(self.groupBox_7)
        self.Apply_power.setGeometry(QtCore.QRect(130, 20, 61, 17))
        self.Apply_power.setObjectName(_fromUtf8("Apply_power"))
        self.Apply_gamma = QtGui.QRadioButton(self.groupBox_7)
        self.Apply_gamma.setEnabled(True)
        self.Apply_gamma.setGeometry(QtCore.QRect(210, 20, 71, 17))
        self.Apply_gamma.setObjectName(_fromUtf8("Apply_gamma"))
        self.groupBox_24 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_24.setGeometry(QtCore.QRect(50, 80, 691, 51))
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.alfa = QtGui.QLineEdit(self.groupBox_24)
        self.alfa.setEnabled(False)
        self.alfa.setGeometry(QtCore.QRect(50, 20, 81, 20))
        self.alfa.setText(_fromUtf8(""))
        self.alfa.setObjectName(_fromUtf8("alfa"))
        self.lblnodematch_11 = QtGui.QLabel(self.groupBox_24)
        self.lblnodematch_11.setGeometry(QtCore.QRect(20, 20, 31, 16))
        self.lblnodematch_11.setObjectName(_fromUtf8("lblnodematch_11"))
        self.beta = QtGui.QLineEdit(self.groupBox_24)
        self.beta.setGeometry(QtCore.QRect(170, 20, 81, 20))
        self.beta.setText(_fromUtf8(""))
        self.beta.setObjectName(_fromUtf8("beta"))
        self.lblnodematch_12 = QtGui.QLabel(self.groupBox_24)
        self.lblnodematch_12.setGeometry(QtCore.QRect(140, 20, 31, 16))
        self.lblnodematch_12.setObjectName(_fromUtf8("lblnodematch_12"))
        self.find_friction_factors = QtGui.QPushButton(self.groupBox_24)
        self.find_friction_factors.setGeometry(QtCore.QRect(260, 20, 101, 23))
        self.find_friction_factors.setObjectName(_fromUtf8("find_friction_factors"))
        self.friction_factors = QtGui.QLineEdit(self.groupBox_24)
        self.friction_factors.setGeometry(QtCore.QRect(370, 20, 311, 20))
        self.friction_factors.setObjectName(_fromUtf8("friction_factors"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(50, 150, 341, 151))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.productions_apply = QtGui.QComboBox(self.groupBox_6)
        self.productions_apply.setGeometry(QtCore.QRect(110, 90, 211, 22))
        self.productions_apply.setObjectName(_fromUtf8("productions_apply"))
        self.layer_vectors_apply = QtGui.QComboBox(self.groupBox_6)
        self.layer_vectors_apply.setGeometry(QtCore.QRect(110, 30, 211, 22))
        self.layer_vectors_apply.setObjectName(_fromUtf8("layer_vectors_apply"))
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.attractions_apply = QtGui.QComboBox(self.groupBox_6)
        self.attractions_apply.setGeometry(QtCore.QRect(110, 120, 211, 22))
        self.attractions_apply.setObjectName(_fromUtf8("attractions_apply"))
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.zone_vectors_apply = QtGui.QComboBox(self.groupBox_6)
        self.zone_vectors_apply.setGeometry(QtCore.QRect(110, 60, 211, 22))
        self.zone_vectors_apply.setObjectName(_fromUtf8("zone_vectors_apply"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(400, 150, 341, 151))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.impedance_to_apply = QtGui.QComboBox(self.groupBox_8)
        self.impedance_to_apply.setEnabled(True)
        self.impedance_to_apply.setGeometry(QtCore.QRect(110, 90, 211, 22))
        self.impedance_to_apply.setMaxVisibleItems(10)
        self.impedance_to_apply.setObjectName(_fromUtf8("impedance_to_apply"))
        self.impedance_from_apply = QtGui.QComboBox(self.groupBox_8)
        self.impedance_from_apply.setGeometry(QtCore.QRect(110, 60, 211, 22))
        self.impedance_from_apply.setMaxVisibleItems(10)
        self.impedance_from_apply.setObjectName(_fromUtf8("impedance_from_apply"))
        self.lblareamatch_4 = QtGui.QLabel(self.groupBox_8)
        self.lblareamatch_4.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.lblareamatch_4.setObjectName(_fromUtf8("lblareamatch_4"))
        self.lblnodematch_2 = QtGui.QLabel(self.groupBox_8)
        self.lblnodematch_2.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.lblnodematch_2.setObjectName(_fromUtf8("lblnodematch_2"))
        self.impedance_layer_apply = QtGui.QComboBox(self.groupBox_8)
        self.impedance_layer_apply.setGeometry(QtCore.QRect(110, 30, 211, 22))
        self.impedance_layer_apply.setMaxVisibleItems(10)
        self.impedance_layer_apply.setObjectName(_fromUtf8("impedance_layer_apply"))
        self.impedance_cost_apply = QtGui.QComboBox(self.groupBox_8)
        self.impedance_cost_apply.setEnabled(True)
        self.impedance_cost_apply.setGeometry(QtCore.QRect(110, 120, 211, 22))
        self.impedance_cost_apply.setMaxVisibleItems(10)
        self.impedance_cost_apply.setObjectName(_fromUtf8("impedance_cost_apply"))
        self.lblareamatch_5 = QtGui.QLabel(self.groupBox_8)
        self.lblareamatch_5.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.lblareamatch_5.setObjectName(_fromUtf8("lblareamatch_5"))
        self.lblareamatch_6 = QtGui.QLabel(self.groupBox_8)
        self.lblareamatch_6.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.lblareamatch_6.setObjectName(_fromUtf8("lblareamatch_6"))
        self.find_apply_gravity_result = QtGui.QPushButton(self.tab_3)
        self.find_apply_gravity_result.setGeometry(QtCore.QRect(50, 320, 81, 23))
        self.find_apply_gravity_result.setObjectName(_fromUtf8("find_apply_gravity_result"))
        self.apply_gravity_result = QtGui.QLineEdit(self.tab_3)
        self.apply_gravity_result.setGeometry(QtCore.QRect(140, 320, 601, 20))
        self.apply_gravity_result.setObjectName(_fromUtf8("apply_gravity_result"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.fratar_result = QtGui.QLineEdit(self.tab_4)
        self.fratar_result.setGeometry(QtCore.QRect(380, 230, 331, 20))
        self.fratar_result.setObjectName(_fromUtf8("fratar_result"))
        self.find_fratar_result = QtGui.QPushButton(self.tab_4)
        self.find_fratar_result.setGeometry(QtCore.QRect(290, 220, 71, 31))
        self.find_fratar_result.setObjectName(_fromUtf8("find_fratar_result"))
        self.groupBox_25 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_25.setGeometry(QtCore.QRect(400, 50, 321, 151))
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.inputmatrix_to_fratar = QtGui.QComboBox(self.groupBox_25)
        self.inputmatrix_to_fratar.setEnabled(True)
        self.inputmatrix_to_fratar.setGeometry(QtCore.QRect(90, 90, 211, 22))
        self.inputmatrix_to_fratar.setMaxVisibleItems(10)
        self.inputmatrix_to_fratar.setObjectName(_fromUtf8("inputmatrix_to_fratar"))
        self.inputmatrix_from_fratar = QtGui.QComboBox(self.groupBox_25)
        self.inputmatrix_from_fratar.setGeometry(QtCore.QRect(90, 60, 211, 22))
        self.inputmatrix_from_fratar.setMaxVisibleItems(10)
        self.inputmatrix_from_fratar.setObjectName(_fromUtf8("inputmatrix_from_fratar"))
        self.lblareamatch_22 = QtGui.QLabel(self.groupBox_25)
        self.lblareamatch_22.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.lblareamatch_22.setObjectName(_fromUtf8("lblareamatch_22"))
        self.lblnodematch_13 = QtGui.QLabel(self.groupBox_25)
        self.lblnodematch_13.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.lblnodematch_13.setObjectName(_fromUtf8("lblnodematch_13"))
        self.inputmatrix_fratar = QtGui.QComboBox(self.groupBox_25)
        self.inputmatrix_fratar.setGeometry(QtCore.QRect(90, 30, 211, 22))
        self.inputmatrix_fratar.setMaxVisibleItems(10)
        self.inputmatrix_fratar.setObjectName(_fromUtf8("inputmatrix_fratar"))
        self.inputmatrix_flow_fratar = QtGui.QComboBox(self.groupBox_25)
        self.inputmatrix_flow_fratar.setEnabled(True)
        self.inputmatrix_flow_fratar.setGeometry(QtCore.QRect(90, 120, 211, 22))
        self.inputmatrix_flow_fratar.setMaxVisibleItems(10)
        self.inputmatrix_flow_fratar.setObjectName(_fromUtf8("inputmatrix_flow_fratar"))
        self.lblareamatch_23 = QtGui.QLabel(self.groupBox_25)
        self.lblareamatch_23.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.lblareamatch_23.setObjectName(_fromUtf8("lblareamatch_23"))
        self.lblareamatch_24 = QtGui.QLabel(self.groupBox_25)
        self.lblareamatch_24.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.lblareamatch_24.setObjectName(_fromUtf8("lblareamatch_24"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(40, 50, 321, 151))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.productions_fratar = QtGui.QComboBox(self.groupBox_10)
        self.productions_fratar.setGeometry(QtCore.QRect(90, 90, 211, 22))
        self.productions_fratar.setObjectName(_fromUtf8("productions_fratar"))
        self.layer_vectors_fratar = QtGui.QComboBox(self.groupBox_10)
        self.layer_vectors_fratar.setGeometry(QtCore.QRect(90, 30, 211, 22))
        self.layer_vectors_fratar.setObjectName(_fromUtf8("layer_vectors_fratar"))
        self.label_11 = QtGui.QLabel(self.groupBox_10)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_10)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_10)
        self.label_13.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.attractions_fratar = QtGui.QComboBox(self.groupBox_10)
        self.attractions_fratar.setGeometry(QtCore.QRect(90, 120, 211, 22))
        self.attractions_fratar.setObjectName(_fromUtf8("attractions_fratar"))
        self.label_14 = QtGui.QLabel(self.groupBox_10)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.zones_fratar = QtGui.QComboBox(self.groupBox_10)
        self.zones_fratar.setGeometry(QtCore.QRect(90, 60, 211, 22))
        self.zones_fratar.setObjectName(_fromUtf8("zones_fratar"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 210, 251, 51))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.yes_initialization = QtGui.QRadioButton(self.groupBox_9)
        self.yes_initialization.setEnabled(True)
        self.yes_initialization.setGeometry(QtCore.QRect(90, 20, 51, 17))
        self.yes_initialization.setObjectName(_fromUtf8("yes_initialization"))
        self.no_initialization = QtGui.QRadioButton(self.groupBox_9)
        self.no_initialization.setGeometry(QtCore.QRect(20, 20, 51, 17))
        self.no_initialization.setChecked(True)
        self.no_initialization.setObjectName(_fromUtf8("no_initialization"))
        self.initialization_value = QtGui.QLineEdit(self.groupBox_9)
        self.initialization_value.setEnabled(False)
        self.initialization_value.setGeometry(QtCore.QRect(160, 20, 61, 20))
        self.initialization_value.setObjectName(_fromUtf8("initialization_value"))
        self.apply_fratar = QtGui.QPushButton(self.tab_4)
        self.apply_fratar.setGeometry(QtCore.QRect(30, 290, 681, 23))
        self.apply_fratar.setObjectName(_fromUtf8("apply_fratar"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.max_impedance = QtGui.QLineEdit(self.tab_2)
        self.max_impedance.setGeometry(QtCore.QRect(170, 26, 141, 20))
        self.max_impedance.setObjectName(_fromUtf8("max_impedance"))
        self.lblnodematch_9 = QtGui.QLabel(self.tab_2)
        self.lblnodematch_9.setGeometry(QtCore.QRect(40, 56, 101, 16))
        self.lblnodematch_9.setObjectName(_fromUtf8("lblnodematch_9"))
        self.lblnodematch_4 = QtGui.QLabel(self.tab_2)
        self.lblnodematch_4.setGeometry(QtCore.QRect(40, 26, 121, 16))
        self.lblnodematch_4.setObjectName(_fromUtf8("lblnodematch_4"))
        self.max_iterations = QtGui.QLineEdit(self.tab_2)
        self.max_iterations.setGeometry(QtCore.QRect(170, 56, 141, 20))
        self.max_iterations.setObjectName(_fromUtf8("max_iterations"))
        self.lblnodematch_14 = QtGui.QLabel(self.tab_2)
        self.lblnodematch_14.setGeometry(QtCore.QRect(40, 90, 101, 16))
        self.lblnodematch_14.setObjectName(_fromUtf8("lblnodematch_14"))
        self.max_error = QtGui.QLineEdit(self.tab_2)
        self.max_error.setGeometry(QtCore.QRect(170, 90, 141, 20))
        self.max_error.setObjectName(_fromUtf8("max_error"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.progress_label2 = QtGui.QLabel(self.tab_5)
        self.progress_label2.setGeometry(QtCore.QRect(400, 50, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label2.setFont(font)
        self.progress_label2.setObjectName(_fromUtf8("progress_label2"))
        self.progressbar = QtGui.QProgressBar(self.tab_5)
        self.progressbar.setEnabled(True)
        self.progressbar.setGeometry(QtCore.QRect(20, 20, 361, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar.setPalette(palette)
        self.progressbar.setProperty("value", 0)
        self.progressbar.setTextVisible(True)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))
        self.progress_label = QtGui.QLabel(self.tab_5)
        self.progress_label.setGeometry(QtCore.QRect(400, 20, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName(_fromUtf8("progress_label"))
        self.progressbar2 = QtGui.QProgressBar(self.tab_5)
        self.progressbar2.setEnabled(True)
        self.progressbar2.setGeometry(QtCore.QRect(20, 50, 361, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar2.setPalette(palette)
        self.progressbar2.setProperty("value", 0)
        self.progressbar2.setTextVisible(True)
        self.progressbar2.setObjectName(_fromUtf8("progressbar2"))
        self.progress_label3 = QtGui.QLabel(self.tab_5)
        self.progress_label3.setGeometry(QtCore.QRect(400, 80, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label3.setFont(font)
        self.progress_label3.setObjectName(_fromUtf8("progress_label3"))
        self.progressbar3 = QtGui.QProgressBar(self.tab_5)
        self.progressbar3.setEnabled(True)
        self.progressbar3.setGeometry(QtCore.QRect(20, 80, 361, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar3.setPalette(palette)
        self.progressbar3.setProperty("value", 0)
        self.progressbar3.setTextVisible(True)
        self.progressbar3.setObjectName(_fromUtf8("progressbar3"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))

        self.retranslateUi(trip_distribution)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(trip_distribution)

    def retranslateUi(self, trip_distribution):
        trip_distribution.setWindowTitle(_translate("trip_distribution", "AequilibraE  -  Trip distribution methods", None))
        self.cancel.setText(_translate("trip_distribution", "CLOSE", None))
        self.calibrate_gravity.setText(_translate("trip_distribution", "CALIBRATE", None))
        self.groupBox.setTitle(_translate("trip_distribution", "Model Type", None))
        self.calib_friction.setText(_translate("trip_distribution", "Friction Factors", None))
        self.calib_gravity.setText(_translate("trip_distribution", "Synthetic gravity", None))
        self.groupBox_3.setTitle(_translate("trip_distribution", "Impedance matrix", None))
        self.lblareamatch.setText(_translate("trip_distribution", "From", None))
        self.lblnodematch.setText(_translate("trip_distribution", "Matrix", None))
        self.lblareamatch_2.setText(_translate("trip_distribution", "To", None))
        self.lblareamatch_3.setText(_translate("trip_distribution", "Impedance", None))
        self.groupBox_5.setTitle(_translate("trip_distribution", "Deterrence Function", None))
        self.expo.setText(_translate("trip_distribution", "Exponential", None))
        self.power.setText(_translate("trip_distribution", "Power", None))
        self.gamma.setText(_translate("trip_distribution", "Gamma", None))
        self.groupBox_23.setTitle(_translate("trip_distribution", "Input Matrix", None))
        self.lblareamatch_19.setText(_translate("trip_distribution", "From", None))
        self.lblnodematch_10.setText(_translate("trip_distribution", "Matrix", None))
        self.lblareamatch_20.setText(_translate("trip_distribution", "To", None))
        self.lblareamatch_21.setText(_translate("trip_distribution", "Flow", None))
        self.find_calibrate_gravity_result.setText(_translate("trip_distribution", "Result File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("trip_distribution", "Gravity calibration", None))
        self.apply_gravity.setText(_translate("trip_distribution", "APPLY MODEL", None))
        self.groupBox_4.setTitle(_translate("trip_distribution", "Model Type", None))
        self.apply_friction.setText(_translate("trip_distribution", "Friction Factors", None))
        self.apply_syntethic.setText(_translate("trip_distribution", "Synthetic gravity", None))
        self.groupBox_7.setTitle(_translate("trip_distribution", "Deterrence Function", None))
        self.Apply_expo.setText(_translate("trip_distribution", "Exponential", None))
        self.Apply_power.setText(_translate("trip_distribution", "Power", None))
        self.Apply_gamma.setText(_translate("trip_distribution", "Gamma", None))
        self.groupBox_24.setTitle(_translate("trip_distribution", "Model parameters", None))
        self.lblnodematch_11.setText(_translate("trip_distribution", "Alfa", None))
        self.lblnodematch_12.setText(_translate("trip_distribution", "Beta", None))
        self.find_friction_factors.setText(_translate("trip_distribution", "Friction Factors", None))
        self.groupBox_6.setTitle(_translate("trip_distribution", "Vectors", None))
        self.label_8.setText(_translate("trip_distribution", "Productions", None))
        self.label_9.setText(_translate("trip_distribution", "Table", None))
        self.label_10.setText(_translate("trip_distribution", "Attractions", None))
        self.label_24.setText(_translate("trip_distribution", "Zone", None))
        self.groupBox_8.setTitle(_translate("trip_distribution", "Impedance matrix", None))
        self.lblareamatch_4.setText(_translate("trip_distribution", "From", None))
        self.lblnodematch_2.setText(_translate("trip_distribution", "Matrix", None))
        self.lblareamatch_5.setText(_translate("trip_distribution", "To", None))
        self.lblareamatch_6.setText(_translate("trip_distribution", "Impedance", None))
        self.find_apply_gravity_result.setText(_translate("trip_distribution", "Result File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("trip_distribution", "Gravity application", None))
        self.find_fratar_result.setText(_translate("trip_distribution", "Result File", None))
        self.groupBox_25.setTitle(_translate("trip_distribution", "Seed Matrix", None))
        self.lblareamatch_22.setText(_translate("trip_distribution", "From", None))
        self.lblnodematch_13.setText(_translate("trip_distribution", "Matrix", None))
        self.lblareamatch_23.setText(_translate("trip_distribution", "To", None))
        self.lblareamatch_24.setText(_translate("trip_distribution", "Flow", None))
        self.groupBox_10.setTitle(_translate("trip_distribution", "Vectors", None))
        self.label_11.setText(_translate("trip_distribution", "Productions", None))
        self.label_12.setText(_translate("trip_distribution", "Table", None))
        self.label_13.setText(_translate("trip_distribution", "Attractions", None))
        self.label_14.setText(_translate("trip_distribution", "Zones", None))
        self.groupBox_9.setTitle(_translate("trip_distribution", "Initialization", None))
        self.yes_initialization.setText(_translate("trip_distribution", "Yes", None))
        self.no_initialization.setText(_translate("trip_distribution", "No", None))
        self.initialization_value.setText(_translate("trip_distribution", "0", None))
        self.apply_fratar.setText(_translate("trip_distribution", "APPLY MODEL", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("trip_distribution", "Fratar", None))
        self.max_impedance.setText(_translate("trip_distribution", "1000000", None))
        self.lblnodematch_9.setText(_translate("trip_distribution", "Model Iterations", None))
        self.lblnodematch_4.setText(_translate("trip_distribution", "Maximum trip length", None))
        self.max_iterations.setText(_translate("trip_distribution", "1000", None))
        self.lblnodematch_14.setText(_translate("trip_distribution", "Convergence level", None))
        self.max_error.setText(_translate("trip_distribution", "0.001", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("trip_distribution", "Global parameters", None))
        self.progress_label2.setText(_translate("trip_distribution", "Status Message 2", None))
        self.progress_label.setText(_translate("trip_distribution", "Status Message 1", None))
        self.progress_label3.setText(_translate("trip_distribution", "Status Message 3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("trip_distribution", "Status", None))

