# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_TQ_NetPrep.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TQ_NetPrep(object):
    def setupUi(self, TQ_NetPrep):
        TQ_NetPrep.setObjectName(_fromUtf8("TQ_NetPrep"))
        TQ_NetPrep.setWindowModality(QtCore.Qt.ApplicationModal)
        TQ_NetPrep.resize(774, 311)
        TQ_NetPrep.setModal(True)
        self.groupBox = QtGui.QGroupBox(TQ_NetPrep)
        self.groupBox.setGeometry(QtCore.QRect(20, 140, 741, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.nodelayers = QtGui.QComboBox(self.groupBox)
        self.nodelayers.setGeometry(QtCore.QRect(164, 56, 541, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.nodelayers.setFont(font)
        self.nodelayers.setObjectName(_fromUtf8("nodelayers"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(25, 96, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.node_fields = QtGui.QComboBox(self.groupBox)
        self.node_fields.setGeometry(QtCore.QRect(164, 91, 541, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.node_fields.setFont(font)
        self.node_fields.setObjectName(_fromUtf8("node_fields"))
        self.radioUseNodes = QtGui.QRadioButton(self.groupBox)
        self.radioUseNodes.setGeometry(QtCore.QRect(350, 24, 151, 17))
        self.radioUseNodes.setChecked(False)
        self.radioUseNodes.setObjectName(_fromUtf8("radioUseNodes"))
        self.radioNewNodes = QtGui.QRadioButton(self.groupBox)
        self.radioNewNodes.setGeometry(QtCore.QRect(172, 23, 171, 17))
        self.radioNewNodes.setChecked(True)
        self.radioNewNodes.setObjectName(_fromUtf8("radioNewNodes"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(25, 95, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.np_node_start = QtGui.QLineEdit(self.groupBox)
        self.np_node_start.setEnabled(False)
        self.np_node_start.setGeometry(QtCore.QRect(179, 91, 71, 24))
        self.np_node_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.np_node_start.setObjectName(_fromUtf8("np_node_start"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(25, 62, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(25, 58, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.OutNodes = QtGui.QLineEdit(self.groupBox)
        self.OutNodes.setGeometry(QtCore.QRect(135, 56, 561, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OutNodes.setFont(font)
        self.OutNodes.setText(_fromUtf8(""))
        self.OutNodes.setObjectName(_fromUtf8("OutNodes"))
        self.groupBox_2 = QtGui.QGroupBox(TQ_NetPrep)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 741, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 31, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.linelayers = QtGui.QComboBox(self.groupBox_2)
        self.linelayers.setGeometry(QtCore.QRect(149, 30, 561, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.linelayers.setFont(font)
        self.linelayers.setObjectName(_fromUtf8("linelayers"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 65, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.OutLinks = QtGui.QLineEdit(self.groupBox_2)
        self.OutLinks.setGeometry(QtCore.QRect(150, 64, 561, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OutLinks.setFont(font)
        self.OutLinks.setText(_fromUtf8(""))
        self.OutLinks.setObjectName(_fromUtf8("OutLinks"))
        self.progressbar = QtGui.QProgressBar(TQ_NetPrep)
        self.progressbar.setGeometry(QtCore.QRect(22, 279, 261, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar.setPalette(palette)
        self.progressbar.setProperty("value", 0)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))
        self.progress_label = QtGui.QLabel(TQ_NetPrep)
        self.progress_label.setGeometry(QtCore.QRect(300, 280, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label.setFont(font)
        self.progress_label.setText(_fromUtf8(""))
        self.progress_label.setObjectName(_fromUtf8("progress_label"))
        self.pushOK = QtGui.QPushButton(TQ_NetPrep)
        self.pushOK.setGeometry(QtCore.QRect(612, 279, 75, 23))
        self.pushOK.setObjectName(_fromUtf8("pushOK"))
        self.pushClose = QtGui.QPushButton(TQ_NetPrep)
        self.pushClose.setGeometry(QtCore.QRect(690, 279, 75, 23))
        self.pushClose.setObjectName(_fromUtf8("pushClose"))
        self.label_3.setBuddy(self.label_3)

        self.retranslateUi(TQ_NetPrep)
        QtCore.QMetaObject.connectSlotsByName(TQ_NetPrep)

    def retranslateUi(self, TQ_NetPrep):
        TQ_NetPrep.setWindowTitle(_translate("TQ_NetPrep", "AequilibraE - Network Preparation Toolbox                                        www.aequilibrae.com", None))
        self.groupBox.setTitle(_translate("TQ_NetPrep", "Nodes layer", None))
        self.label_2.setText(_translate("TQ_NetPrep", "Node Layer fields", None))
        self.radioUseNodes.setText(_translate("TQ_NetPrep", "Use node layer", None))
        self.radioNewNodes.setText(_translate("TQ_NetPrep", "Create node layer", None))
        self.label_3.setText(_translate("TQ_NetPrep", "Node numbering start", None))
        self.np_node_start.setText(_translate("TQ_NetPrep", "0", None))
        self.label_4.setText(_translate("TQ_NetPrep", "Node Layer", None))
        self.label_9.setText(_translate("TQ_NetPrep", "Node layer name", None))
        self.OutNodes.setPlaceholderText(_translate("TQ_NetPrep", "Enter name for node layer with centroids", None))
        self.groupBox_2.setTitle(_translate("TQ_NetPrep", "Links layer", None))
        self.label.setText(_translate("TQ_NetPrep", "Network Layer", None))
        self.label_8.setText(_translate("TQ_NetPrep", "Line layer name", None))
        self.OutLinks.setPlaceholderText(_translate("TQ_NetPrep", "Enter name for new network layer", None))
        self.pushOK.setText(_translate("TQ_NetPrep", "Run!", None))
        self.pushClose.setText(_translate("TQ_NetPrep", "Close", None))

