# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Traffic_Assignment.ui'
#
# Created: Tue Mar 01 22:40:52 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Traffic_Assignment(object):
    def setupUi(self, Traffic_Assignment):
        Traffic_Assignment.setObjectName(_fromUtf8("Traffic_Assignment"))
        Traffic_Assignment.resize(721, 411)
        self.tabWidget = QtGui.QTabWidget(Traffic_Assignment)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 701, 391))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.radio_layer_matrix = QtGui.QRadioButton(self.widget)
        self.radio_layer_matrix.setGeometry(QtCore.QRect(20, 21, 151, 17))
        self.radio_layer_matrix.setObjectName(_fromUtf8("radio_layer_matrix"))
        self.radio_npy_omx_matrix = QtGui.QRadioButton(self.widget)
        self.radio_npy_omx_matrix.setGeometry(QtCore.QRect(180, 20, 171, 17))
        self.radio_npy_omx_matrix.setObjectName(_fromUtf8("radio_npy_omx_matrix"))
        self.omx_box = QtGui.QGroupBox(self.widget)
        self.omx_box.setEnabled(True)
        self.omx_box.setGeometry(QtCore.QRect(10, 50, 671, 311))
        self.omx_box.setObjectName(_fromUtf8("omx_box"))
        self.lbl_totals = QtGui.QLabel(self.omx_box)
        self.lbl_totals.setGeometry(QtCore.QRect(8, 76, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_totals.setFont(font)
        self.lbl_totals.setText(_fromUtf8(""))
        self.lbl_totals.setObjectName(_fromUtf8("lbl_totals"))
        self.lbl_intra = QtGui.QLabel(self.omx_box)
        self.lbl_intra.setGeometry(QtCore.QRect(20, 96, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_intra.setFont(font)
        self.lbl_intra.setText(_fromUtf8(""))
        self.lbl_intra.setObjectName(_fromUtf8("lbl_intra"))
        self.lbl_omx_core = QtGui.QLabel(self.omx_box)
        self.lbl_omx_core.setGeometry(QtCore.QRect(419, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_omx_core.setFont(font)
        self.lbl_omx_core.setObjectName(_fromUtf8("lbl_omx_core"))
        self.matrix_cores_selector = QtGui.QComboBox(self.omx_box)
        self.matrix_cores_selector.setGeometry(QtCore.QRect(499, 30, 161, 22))
        self.matrix_cores_selector.setObjectName(_fromUtf8("matrix_cores_selector"))
        self.lbl_matrix_loaded = QtGui.QLabel(self.omx_box)
        self.lbl_matrix_loaded.setGeometry(QtCore.QRect(10, 220, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_matrix_loaded.setFont(font)
        self.lbl_matrix_loaded.setWordWrap(True)
        self.lbl_matrix_loaded.setObjectName(_fromUtf8("lbl_matrix_loaded"))
        self.lbl_inter = QtGui.QLabel(self.omx_box)
        self.lbl_inter.setGeometry(QtCore.QRect(20, 116, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_inter.setFont(font)
        self.lbl_inter.setText(_fromUtf8(""))
        self.lbl_inter.setObjectName(_fromUtf8("lbl_inter"))
        self.but_load_new_matrix = QtGui.QPushButton(self.omx_box)
        self.but_load_new_matrix.setGeometry(QtCore.QRect(20, 30, 261, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_new_matrix.setFont(font)
        self.but_load_new_matrix.setObjectName(_fromUtf8("but_load_new_matrix"))
        self.display_matrix = QtGui.QCheckBox(self.omx_box)
        self.display_matrix.setGeometry(QtCore.QRect(300, 30, 101, 17))
        self.display_matrix.setObjectName(_fromUtf8("display_matrix"))
        self.matrix_viewer = QtGui.QTableView(self.omx_box)
        self.matrix_viewer.setGeometry(QtCore.QRect(180, 70, 481, 231))
        self.matrix_viewer.setObjectName(_fromUtf8("matrix_viewer"))
        self.layer_matrix_box = QtGui.QGroupBox(self.widget)
        self.layer_matrix_box.setGeometry(QtCore.QRect(10, 50, 331, 181))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.layer_matrix_box.setFont(font)
        self.layer_matrix_box.setObjectName(_fromUtf8("layer_matrix_box"))
        self.matrix_flow = QtGui.QComboBox(self.layer_matrix_box)
        self.matrix_flow.setEnabled(True)
        self.matrix_flow.setGeometry(QtCore.QRect(90, 140, 211, 22))
        self.matrix_flow.setMaxVisibleItems(10)
        self.matrix_flow.setObjectName(_fromUtf8("matrix_flow"))
        self.lblareamatch_20 = QtGui.QLabel(self.layer_matrix_box)
        self.lblareamatch_20.setGeometry(QtCore.QRect(60, 101, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblareamatch_20.setFont(font)
        self.lblareamatch_20.setObjectName(_fromUtf8("lblareamatch_20"))
        self.matrix_to = QtGui.QComboBox(self.layer_matrix_box)
        self.matrix_to.setEnabled(True)
        self.matrix_to.setGeometry(QtCore.QRect(90, 100, 211, 22))
        self.matrix_to.setMaxVisibleItems(10)
        self.matrix_to.setObjectName(_fromUtf8("matrix_to"))
        self.lblareamatch_21 = QtGui.QLabel(self.layer_matrix_box)
        self.lblareamatch_21.setGeometry(QtCore.QRect(49, 142, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblareamatch_21.setFont(font)
        self.lblareamatch_21.setObjectName(_fromUtf8("lblareamatch_21"))
        self.matrix_from = QtGui.QComboBox(self.layer_matrix_box)
        self.matrix_from.setGeometry(QtCore.QRect(90, 64, 211, 22))
        self.matrix_from.setMaxVisibleItems(10)
        self.matrix_from.setObjectName(_fromUtf8("matrix_from"))
        self.inputmatrix = QtGui.QComboBox(self.layer_matrix_box)
        self.inputmatrix.setGeometry(QtCore.QRect(90, 30, 211, 22))
        self.inputmatrix.setMaxVisibleItems(10)
        self.inputmatrix.setObjectName(_fromUtf8("inputmatrix"))
        self.lblareamatch_19 = QtGui.QLabel(self.layer_matrix_box)
        self.lblareamatch_19.setGeometry(QtCore.QRect(46, 66, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblareamatch_19.setFont(font)
        self.lblareamatch_19.setObjectName(_fromUtf8("lblareamatch_19"))
        self.lblnodematch_10 = QtGui.QLabel(self.layer_matrix_box)
        self.lblnodematch_10.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_10.setFont(font)
        self.lblnodematch_10.setObjectName(_fromUtf8("lblnodematch_10"))
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.capacity_field = QtGui.QComboBox(self.tab_2)
        self.capacity_field.setGeometry(QtCore.QRect(150, 140, 391, 22))
        self.capacity_field.setObjectName(_fromUtf8("capacity_field"))
        self.lblnodematch_11 = QtGui.QLabel(self.tab_2)
        self.lblnodematch_11.setGeometry(QtCore.QRect(50, 70, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_11.setFont(font)
        self.lblnodematch_11.setObjectName(_fromUtf8("lblnodematch_11"))
        self.network_layer = QtGui.QComboBox(self.tab_2)
        self.network_layer.setGeometry(QtCore.QRect(150, 70, 391, 22))
        self.network_layer.setMaxVisibleItems(10)
        self.network_layer.setObjectName(_fromUtf8("network_layer"))
        self.minimizing_field = QtGui.QComboBox(self.tab_2)
        self.minimizing_field.setGeometry(QtCore.QRect(150, 105, 391, 22))
        self.minimizing_field.setObjectName(_fromUtf8("minimizing_field"))
        self.capacity_lbl = QtGui.QLabel(self.tab_2)
        self.capacity_lbl.setGeometry(QtCore.QRect(50, 143, 161, 16))
        self.capacity_lbl.setObjectName(_fromUtf8("capacity_lbl"))
        self.ba_time_lbl = QtGui.QLabel(self.tab_2)
        self.ba_time_lbl.setGeometry(QtCore.QRect(50, 108, 151, 16))
        self.ba_time_lbl.setObjectName(_fromUtf8("ba_time_lbl"))
        self.no_connectors_in_graph = QtGui.QCheckBox(self.tab_2)
        self.no_connectors_in_graph.setGeometry(QtCore.QRect(370, 340, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.no_connectors_in_graph.setFont(font)
        self.no_connectors_in_graph.setChecked(True)
        self.no_connectors_in_graph.setObjectName(_fromUtf8("no_connectors_in_graph"))
        self.load_graph_from_file = QtGui.QPushButton(self.tab_2)
        self.load_graph_from_file.setGeometry(QtCore.QRect(30, 30, 91, 23))
        self.load_graph_from_file.setObjectName(_fromUtf8("load_graph_from_file"))
        self.lbl_graphfile = QtGui.QLabel(self.tab_2)
        self.lbl_graphfile.setGeometry(QtCore.QRect(153, 32, 391, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_graphfile.setFont(font)
        self.lbl_graphfile.setObjectName(_fromUtf8("lbl_graphfile"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.bpr_box = QtGui.QGroupBox(self.tab_3)
        self.bpr_box.setGeometry(QtCore.QRect(30, 120, 501, 101))
        self.bpr_box.setObjectName(_fromUtf8("bpr_box"))
        self.label_9 = QtGui.QLabel(self.bpr_box)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_11 = QtGui.QLabel(self.bpr_box)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.bpr_box)
        self.label_12.setGeometry(QtCore.QRect(80, 20, 71, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.bpr_alfa = QtGui.QLineEdit(self.bpr_box)
        self.bpr_alfa.setGeometry(QtCore.QRect(80, 40, 51, 20))
        self.bpr_alfa.setInputMethodHints(QtCore.Qt.ImhNone)
        self.bpr_alfa.setObjectName(_fromUtf8("bpr_alfa"))
        self.bpr_beta = QtGui.QLineEdit(self.bpr_box)
        self.bpr_beta.setGeometry(QtCore.QRect(80, 70, 51, 20))
        self.bpr_beta.setInputMethodHints(QtCore.Qt.ImhNone)
        self.bpr_beta.setObjectName(_fromUtf8("bpr_beta"))
        self.bpr_alfa_link = QtGui.QComboBox(self.bpr_box)
        self.bpr_alfa_link.setGeometry(QtCore.QRect(160, 40, 301, 22))
        self.bpr_alfa_link.setObjectName(_fromUtf8("bpr_alfa_link"))
        self.bpr_beta_link = QtGui.QComboBox(self.bpr_box)
        self.bpr_beta_link.setGeometry(QtCore.QRect(160, 70, 301, 22))
        self.bpr_beta_link.setObjectName(_fromUtf8("bpr_beta_link"))
        self.label_13 = QtGui.QLabel(self.bpr_box)
        self.label_13.setGeometry(QtCore.QRect(230, 20, 71, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.vdf_box = QtGui.QGroupBox(self.tab_3)
        self.vdf_box.setGeometry(QtCore.QRect(30, 50, 501, 61))
        self.vdf_box.setObjectName(_fromUtf8("vdf_box"))
        self.bpr = QtGui.QRadioButton(self.vdf_box)
        self.bpr.setGeometry(QtCore.QRect(20, 30, 51, 17))
        self.bpr.setChecked(True)
        self.bpr.setObjectName(_fromUtf8("bpr"))
        self.algorithms = QtGui.QComboBox(self.tab_3)
        self.algorithms.setGeometry(QtCore.QRect(200, 20, 331, 22))
        self.algorithms.setObjectName(_fromUtf8("algorithms"))
        self.convergence_box = QtGui.QGroupBox(self.tab_3)
        self.convergence_box.setGeometry(QtCore.QRect(30, 230, 501, 61))
        self.convergence_box.setObjectName(_fromUtf8("convergence_box"))
        self.max_iter = QtGui.QLineEdit(self.convergence_box)
        self.max_iter.setGeometry(QtCore.QRect(370, 30, 101, 20))
        self.max_iter.setObjectName(_fromUtf8("max_iter"))
        self.label_6 = QtGui.QLabel(self.convergence_box)
        self.label_6.setGeometry(QtCore.QRect(260, 30, 111, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.convergence_box)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.rel_gap = QtGui.QLineEdit(self.convergence_box)
        self.rel_gap.setGeometry(QtCore.QRect(100, 30, 101, 20))
        self.rel_gap.setObjectName(_fromUtf8("rel_gap"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(50, 20, 131, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.skim_list = QtGui.QTableWidget(self.tab_4)
        self.skim_list.setGeometry(QtCore.QRect(33, 80, 471, 211))
        self.skim_list.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.skim_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.skim_list.setRowCount(0)
        self.skim_list.setColumnCount(2)
        self.skim_list.setObjectName(_fromUtf8("skim_list"))
        item = QtGui.QTableWidgetItem()
        self.skim_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.skim_list.setHorizontalHeaderItem(1, item)
        self.skim_list.verticalHeader().setDefaultSectionSize(27)
        self.add_skim = QtGui.QPushButton(self.tab_4)
        self.add_skim.setGeometry(QtCore.QRect(33, 20, 91, 51))
        self.add_skim.setObjectName(_fromUtf8("add_skim"))
        self.skim_field = QtGui.QComboBox(self.tab_4)
        self.skim_field.setGeometry(QtCore.QRect(203, 34, 301, 22))
        self.skim_field.setObjectName(_fromUtf8("skim_field"))
        self.lblnodematch_12 = QtGui.QLabel(self.tab_4)
        self.lblnodematch_12.setGeometry(QtCore.QRect(140, 37, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblnodematch_12.setFont(font)
        self.lblnodematch_12.setObjectName(_fromUtf8("lblnodematch_12"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.path_list = QtGui.QTableWidget(self.tab_5)
        self.path_list.setEnabled(False)
        self.path_list.setGeometry(QtCore.QRect(33, 80, 631, 211))
        self.path_list.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.path_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.path_list.setRowCount(0)
        self.path_list.setColumnCount(3)
        self.path_list.setObjectName(_fromUtf8("path_list"))
        item = QtGui.QTableWidgetItem()
        self.path_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.path_list.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.path_list.setHorizontalHeaderItem(2, item)
        self.path_list.verticalHeader().setDefaultSectionSize(27)
        self.sel_link_anal_set = QtGui.QComboBox(self.tab_5)
        self.sel_link_anal_set.setEnabled(False)
        self.sel_link_anal_set.setGeometry(QtCore.QRect(250, 15, 411, 22))
        self.sel_link_anal_set.setObjectName(_fromUtf8("sel_link_anal_set"))
        self.select_link_analysis = QtGui.QRadioButton(self.tab_5)
        self.select_link_analysis.setEnabled(False)
        self.select_link_analysis.setGeometry(QtCore.QRect(33, 18, 331, 17))
        self.select_link_analysis.setObjectName(_fromUtf8("select_link_analysis"))
        self.select_link_analysis_4 = QtGui.QRadioButton(self.tab_5)
        self.select_link_analysis_4.setEnabled(False)
        self.select_link_analysis_4.setGeometry(QtCore.QRect(33, 50, 181, 17))
        self.select_link_analysis_4.setObjectName(_fromUtf8("select_link_analysis_4"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_2.setGeometry(QtCore.QRect(27, 90, 651, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.SizeScale_times = QtGui.QRadioButton(self.groupBox_2)
        self.SizeScale_times.setEnabled(False)
        self.SizeScale_times.setGeometry(QtCore.QRect(440, 20, 111, 17))
        self.SizeScale_times.setObjectName(_fromUtf8("SizeScale_times"))
        self.SizeScale_voc = QtGui.QRadioButton(self.groupBox_2)
        self.SizeScale_voc.setEnabled(False)
        self.SizeScale_voc.setGeometry(QtCore.QRect(120, 20, 151, 17))
        self.SizeScale_voc.setObjectName(_fromUtf8("SizeScale_voc"))
        self.SizeScale_tot_vol = QtGui.QRadioButton(self.groupBox_2)
        self.SizeScale_tot_vol.setEnabled(True)
        self.SizeScale_tot_vol.setGeometry(QtCore.QRect(300, 20, 101, 17))
        self.SizeScale_tot_vol.setObjectName(_fromUtf8("SizeScale_tot_vol"))
        self.SizeScale_no_map = QtGui.QRadioButton(self.groupBox_2)
        self.SizeScale_no_map.setGeometry(QtCore.QRect(10, 20, 81, 17))
        self.SizeScale_no_map.setChecked(True)
        self.SizeScale_no_map.setObjectName(_fromUtf8("SizeScale_no_map"))
        self.groupBox = QtGui.QGroupBox(self.tab_6)
        self.groupBox.setGeometry(QtCore.QRect(27, 20, 651, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.theme_voc = QtGui.QRadioButton(self.groupBox)
        self.theme_voc.setEnabled(False)
        self.theme_voc.setGeometry(QtCore.QRect(120, 20, 151, 17))
        self.theme_voc.setObjectName(_fromUtf8("theme_voc"))
        self.theme_tot_vol = QtGui.QRadioButton(self.groupBox)
        self.theme_tot_vol.setEnabled(True)
        self.theme_tot_vol.setGeometry(QtCore.QRect(300, 20, 101, 17))
        self.theme_tot_vol.setObjectName(_fromUtf8("theme_tot_vol"))
        self.theme_times = QtGui.QRadioButton(self.groupBox)
        self.theme_times.setEnabled(False)
        self.theme_times.setGeometry(QtCore.QRect(440, 20, 121, 17))
        self.theme_times.setObjectName(_fromUtf8("theme_times"))
        self.theme_no_map = QtGui.QRadioButton(self.groupBox)
        self.theme_no_map.setGeometry(QtCore.QRect(10, 20, 81, 17))
        self.theme_no_map.setChecked(True)
        self.theme_no_map.setObjectName(_fromUtf8("theme_no_map"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.available_cores = QtGui.QLabel(self.tab)
        self.available_cores.setGeometry(QtCore.QRect(140, 90, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.available_cores.setFont(font)
        self.available_cores.setObjectName(_fromUtf8("available_cores"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(30, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.cpus = QtGui.QComboBox(self.tab)
        self.cpus.setGeometry(QtCore.QRect(70, 87, 61, 22))
        self.cpus.setObjectName(_fromUtf8("cpus"))
        self.do_assignment = QtGui.QPushButton(self.tab)
        self.do_assignment.setGeometry(QtCore.QRect(20, 170, 351, 23))
        self.do_assignment.setObjectName(_fromUtf8("do_assignment"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 170, 131, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.assig_results = QtGui.QLineEdit(self.tab)
        self.assig_results.setGeometry(QtCore.QRect(170, 40, 331, 20))
        self.assig_results.setObjectName(_fromUtf8("assig_results"))
        self.select_result = QtGui.QPushButton(self.tab)
        self.select_result.setGeometry(QtCore.QRect(30, 40, 121, 23))
        self.select_result.setObjectName(_fromUtf8("select_result"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.StatusPage = QtGui.QWidget()
        self.StatusPage.setObjectName(_fromUtf8("StatusPage"))
        self.progressbar3 = QtGui.QProgressBar(self.StatusPage)
        self.progressbar3.setEnabled(True)
        self.progressbar3.setGeometry(QtCore.QRect(10, 100, 331, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar3.setPalette(palette)
        self.progressbar3.setProperty("value", 0)
        self.progressbar3.setTextVisible(True)
        self.progressbar3.setObjectName(_fromUtf8("progressbar3"))
        self.progress_label2 = QtGui.QLabel(self.StatusPage)
        self.progress_label2.setGeometry(QtCore.QRect(360, 70, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label2.setFont(font)
        self.progress_label2.setObjectName(_fromUtf8("progress_label2"))
        self.progress_label1 = QtGui.QLabel(self.StatusPage)
        self.progress_label1.setGeometry(QtCore.QRect(360, 40, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label1.setFont(font)
        self.progress_label1.setObjectName(_fromUtf8("progress_label1"))
        self.progress_label3 = QtGui.QLabel(self.StatusPage)
        self.progress_label3.setGeometry(QtCore.QRect(360, 100, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label3.setFont(font)
        self.progress_label3.setObjectName(_fromUtf8("progress_label3"))
        self.progressbar1 = QtGui.QProgressBar(self.StatusPage)
        self.progressbar1.setEnabled(True)
        self.progressbar1.setGeometry(QtCore.QRect(10, 40, 331, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar1.setPalette(palette)
        self.progressbar1.setProperty("value", 0)
        self.progressbar1.setTextVisible(True)
        self.progressbar1.setObjectName(_fromUtf8("progressbar1"))
        self.progressbar2 = QtGui.QProgressBar(self.StatusPage)
        self.progressbar2.setEnabled(True)
        self.progressbar2.setGeometry(QtCore.QRect(10, 70, 331, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar2.setPalette(palette)
        self.progressbar2.setProperty("value", 0)
        self.progressbar2.setTextVisible(True)
        self.progressbar2.setObjectName(_fromUtf8("progressbar2"))
        self.progress_label0 = QtGui.QLabel(self.StatusPage)
        self.progress_label0.setGeometry(QtCore.QRect(359, 9, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label0.setFont(font)
        self.progress_label0.setObjectName(_fromUtf8("progress_label0"))
        self.progressbar0 = QtGui.QProgressBar(self.StatusPage)
        self.progressbar0.setEnabled(True)
        self.progressbar0.setGeometry(QtCore.QRect(9, 9, 331, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar0.setPalette(palette)
        self.progressbar0.setProperty("value", 0)
        self.progressbar0.setTextVisible(True)
        self.progressbar0.setObjectName(_fromUtf8("progressbar0"))
        self.progress_label4 = QtGui.QLabel(self.StatusPage)
        self.progress_label4.setGeometry(QtCore.QRect(360, 132, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_label4.setFont(font)
        self.progress_label4.setObjectName(_fromUtf8("progress_label4"))
        self.progressbar4 = QtGui.QProgressBar(self.StatusPage)
        self.progressbar4.setEnabled(True)
        self.progressbar4.setGeometry(QtCore.QRect(10, 132, 331, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressbar4.setPalette(palette)
        self.progressbar4.setProperty("value", 0)
        self.progressbar4.setTextVisible(True)
        self.progressbar4.setObjectName(_fromUtf8("progressbar4"))
        self.tabWidget.addTab(self.StatusPage, _fromUtf8(""))

        self.retranslateUi(Traffic_Assignment)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Traffic_Assignment)

    def retranslateUi(self, Traffic_Assignment):
        Traffic_Assignment.setWindowTitle(_translate("Traffic_Assignment", "Traffic Assignment toolbox - Provided by www.xl-optim.com", None))
        self.radio_layer_matrix.setText(_translate("Traffic_Assignment", "Use open file as matrix", None))
        self.radio_npy_omx_matrix.setText(_translate("Traffic_Assignment", "Use Numpy or OMX matrix", None))
        self.omx_box.setTitle(_translate("Traffic_Assignment", "NumPy / OMX matrix", None))
        self.lbl_omx_core.setText(_translate("Traffic_Assignment", "OMX cores", None))
        self.lbl_matrix_loaded.setText(_translate("Traffic_Assignment", "No Matrix Loaded", None))
        self.but_load_new_matrix.setText(_translate("Traffic_Assignment", "Load new matrix", None))
        self.display_matrix.setText(_translate("Traffic_Assignment", "Display Matrix", None))
        self.layer_matrix_box.setTitle(_translate("Traffic_Assignment", "Text format matrix", None))
        self.lblareamatch_20.setText(_translate("Traffic_Assignment", "To", None))
        self.lblareamatch_21.setText(_translate("Traffic_Assignment", "Flow", None))
        self.lblareamatch_19.setText(_translate("Traffic_Assignment", "From", None))
        self.lblnodematch_10.setText(_translate("Traffic_Assignment", "Matrix layer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Traffic_Assignment", "Demand", None))
        self.lblnodematch_11.setText(_translate("Traffic_Assignment", "Line layer", None))
        self.capacity_lbl.setText(_translate("Traffic_Assignment", "Capacity", None))
        self.ba_time_lbl.setText(_translate("Traffic_Assignment", "Minimizing field", None))
        self.no_connectors_in_graph.setText(_translate("Traffic_Assignment", "Prevent flows through centroid connectors", None))
        self.load_graph_from_file.setText(_translate("Traffic_Assignment", "Load Graph", None))
        self.lbl_graphfile.setText(_translate("Traffic_Assignment", "Load graph *.aeg", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Traffic_Assignment", "Network", None))
        self.bpr_box.setTitle(_translate("Traffic_Assignment", "BPR Parameters", None))
        self.label_9.setText(_translate("Traffic_Assignment", "Alfa", None))
        self.label_11.setText(_translate("Traffic_Assignment", "Beta", None))
        self.label_12.setText(_translate("Traffic_Assignment", "Default", None))
        self.bpr_alfa.setText(_translate("Traffic_Assignment", "0.15", None))
        self.bpr_beta.setText(_translate("Traffic_Assignment", "4.0", None))
        self.label_13.setText(_translate("Traffic_Assignment", "Link_specific", None))
        self.vdf_box.setTitle(_translate("Traffic_Assignment", "Volume-Delay function", None))
        self.bpr.setText(_translate("Traffic_Assignment", "BPR", None))
        self.convergence_box.setTitle(_translate("Traffic_Assignment", "Convergence", None))
        self.max_iter.setText(_translate("Traffic_Assignment", "1000", None))
        self.label_6.setText(_translate("Traffic_Assignment", "Maximum iterations", None))
        self.label_7.setText(_translate("Traffic_Assignment", "Relative Gap", None))
        self.rel_gap.setText(_translate("Traffic_Assignment", "0.0001", None))
        self.label.setText(_translate("Traffic_Assignment", "Assignment algorithm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Traffic_Assignment", "Assignment method", None))
        self.skim_list.setAccessibleName(_translate("Traffic_Assignment", "<html><head/><body><p>xcxc</p></body></html>", None))
        item = self.skim_list.horizontalHeaderItem(0)
        item.setText(_translate("Traffic_Assignment", "Skim name", None))
        item = self.skim_list.horizontalHeaderItem(1)
        item.setText(_translate("Traffic_Assignment", "Field", None))
        self.add_skim.setText(_translate("Traffic_Assignment", "Add Skim", None))
        self.lblnodematch_12.setText(_translate("Traffic_Assignment", "Field", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Traffic_Assignment", "Skims", None))
        self.path_list.setAccessibleName(_translate("Traffic_Assignment", "<html><head/><body><p>xcxc</p></body></html>", None))
        item = self.path_list.horizontalHeaderItem(0)
        item.setText(_translate("Traffic_Assignment", "Query Type", None))
        item = self.path_list.horizontalHeaderItem(1)
        item.setText(_translate("Traffic_Assignment", "Query ID", None))
        item = self.path_list.horizontalHeaderItem(2)
        item.setText(_translate("Traffic_Assignment", "Querying element", None))
        self.select_link_analysis.setText(_translate("Traffic_Assignment", "Select link analysis", None))
        self.select_link_analysis_4.setText(_translate("Traffic_Assignment", "Complete path file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Traffic_Assignment", "Path Queries", None))
        self.groupBox_2.setTitle(_translate("Traffic_Assignment", "Line Thickness", None))
        self.SizeScale_times.setText(_translate("Traffic_Assignment", "Final Travel times", None))
        self.SizeScale_voc.setText(_translate("Traffic_Assignment", "Volume Capacity Ratio", None))
        self.SizeScale_tot_vol.setText(_translate("Traffic_Assignment", "Total Volumes", None))
        self.SizeScale_no_map.setText(_translate("Traffic_Assignment", "No theme", None))
        self.groupBox.setTitle(_translate("Traffic_Assignment", "Theme map", None))
        self.theme_voc.setText(_translate("Traffic_Assignment", "Volume Capacity Ratio", None))
        self.theme_tot_vol.setText(_translate("Traffic_Assignment", "Total Volumes", None))
        self.theme_times.setText(_translate("Traffic_Assignment", "Final Travel times", None))
        self.theme_no_map.setText(_translate("Traffic_Assignment", "No theme", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Traffic_Assignment", "Mapping", None))
        self.available_cores.setText(_translate("Traffic_Assignment", "out of XX available cores", None))
        self.label_14.setText(_translate("Traffic_Assignment", "Use", None))
        self.do_assignment.setText(_translate("Traffic_Assignment", "ASSIGN", None))
        self.pushButton_2.setText(_translate("Traffic_Assignment", "CANCEL", None))
        self.select_result.setText(_translate("Traffic_Assignment", "Assignment results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Traffic_Assignment", "Assignment", None))
        self.progress_label2.setText(_translate("Traffic_Assignment", "Status Message 2", None))
        self.progress_label1.setText(_translate("Traffic_Assignment", "Status Message 1", None))
        self.progress_label3.setText(_translate("Traffic_Assignment", "Status Message 3", None))
        self.progress_label0.setText(_translate("Traffic_Assignment", "Status Message 0", None))
        self.progress_label4.setText(_translate("Traffic_Assignment", "Status Message 4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.StatusPage), _translate("Traffic_Assignment", "Status", None))

