name: Test AequilibraE dependency

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  unittest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      max-parallel: 4
      matrix:
        container: ['qgis/qgis:latest', 'qgis/qgis:ltr']
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m venv /tmp/.venv --system-site-packages
          . /tmp/.venv/bin/activate
          python3 -m pip install -U pip setuptools uv
          python3 -m uv pip install "git+https://github.com/AequilibraE/aequilibrae.git@develop"
          touch ./qaequilibrae/packages/aequilibrae_version.txt
          python3 ./ci/dependency_installation.py
          python3 -m uv pip install -r test/requirements_test.txt --constraint ./ci/constraints.txt
          export PYTHONPATH=$(pwd)/qaequilibrae/packages:$PYTHONPATH
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV

      - name: Run tests
        run: |
          . /tmp/.venv/bin/activate
          export PYTHONPATH=$(pwd)/qaequilibrae/packages:$PYTHONPATH
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest --cov-report term --cov-config=.coveragerc --cov=qaequilibrae test
