name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # container: ['qgis/qgis:latest', 'qgis/qgis:3.34', 'qgis/qgis:3.36']
        container: ['qgis/qgis:latest']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt update && apt install -y python3-venv python3-pip
          python3 -m venv --system-site-packages /app/qgis_env

      - name: Install QGIS and related dependencies
        run: |
          source /app/qgis_env/bin/activate
          apt-get install -y qgis python3-qgis qgis-plugin-grass
          ln -s /usr/local/bin/qgis-bin /app/qgis_env/bin/qgis

      - name: Check QGIS installation
        run: /app/qgis_env/bin/qgis --version

      - name: Run your Python script or tests
        run: |
          python3 -m pip install setuptools
          python3 -m pip install -r test/requirements-test.txt
          python3 -m pip install -r ci/requirements-dev.txt
          python3 -c 'from qaequilibrae.download_extra_packages_class import DownloadAll; DownloadAll().install(True)'

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest test -v --tb=short --cov=qaequilibrae
