name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    run: git --version
    strategy:
      max-parallel: 4
      matrix:
        container: [ 'qgis/qgis:latest', 'qgis/qgis:release-3_32']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          python3 -c "from qaequilibrae.download_extra_packages_class import download_all; download_all().install(True)"
          python3 -m pip install -r test/requirements-test.txt
          python3 -m pip install -r ci/requirements-dev.txt

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest test -v --tb=short --cov=qaequilibrae
