name: DevelopmentTests

on:  [pull_request]

jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # container: ['qgis/qgis:latest', 'qgis/qgis:3.34.7']
        container: ['qgis/qgis:latest']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t qaequilibrae .

      - name: Run tests
        run: |
          docker run -v $(pwd):/app -w /app qaequilibrae bash -c "source /app/qgis_env/bin/activate && pip install -r test/requirements-test.txt && python3 ci/dependency_installation.py && python3 -m pytest test -v --tb=short --cov=qaequilibrae"
