name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest_latest:
#    needs: linting
    runs-on: ubuntu-latest
    container: qgis/qgis:latest
    strategy:
      max-parallel: 4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest tests

  unittest_ltr:
#    needs: linting
    runs-on: ubuntu-latest
    container: qgis/qgis:release-3_22
    strategy:
      max-parallel: 4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest tests
