name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        container: [ 'qgis/qgis:latest', 'qgis/qgis:release-3_28']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          python3 -m pip install -r qaequilibrae/requirements.txt
          python3 -m pip install -r requirements/requirements-dev.txt
          python3 -m pip install numpy --upgrade

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest test
