name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        container: [ 'qgis/qgis:latest', 'qgis/qgis:release-3_28']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-dev.txt
          python3 -m pip install numpy --upgrade
          python3 -m pip install git+https://github.com/AequilibraE/aequilibrae@develop

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest test

  packaging:
#    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Build artifact
        run: |
          rm -rf ./tests ./test ./docs .git .devcontainer .github
          mkdir -p /tmp/artifacts
          cd ..
          zip -r /tmp/artifacts/QAequilibraE.zip ./qaequilibrae

      - name: Stores artifacts along with the workflow result
        uses: actions/upload-artifact@v3
        with:
          name: library
          path: /tmp/artifacts/*.zip
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`