name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # container: [ 'qgis/qgis:release-3_34']
        container: [ 'qgis/qgis:latest', 'qgis/qgis:release-3_34']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          chmod +x qaequilibrae/download_extra_packages_class.py
          sudo qaequilibrae/download_extra_packages_class.py

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest test -v --tb=short --cov=qaequilibrae
