name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        container: [ 'qgis/qgis:latest', 'qgis/qgis:3.34.7']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install setuptools --break-system-packages
          python3 -m pip install -r test/requirements-test.txt --break-system-packages
          python3 -m pip install aequilibrae==1.0.1 absl-py immutabledict protobuf --break-system-packages
          python3 -m pip install ortools --no-deps --break-system-packages

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest test -v --tb=short --cov=qaequilibrae
