name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # container: ['qgis/qgis:latest', 'qgis/qgis:3.34.7']
        container: ['qgis/qgis:latest']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install virtualenv --break-system-packages
          python3 -m virtualenv venv
          venv/bin/activate
          python3 -m pip install setuptools
          python3 -m pip install -r test/requirements-test.txt
#          python3 ./ci/dependency_installation.py

      # - name: Run tests
      #   run: |
      #     export QT_QPA_PLATFORM=offscreen
      #     pwd
      #     python3 -m pytest test -v --tb=short --cov=qaequilibrae
