name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        container: [ 'qgis/qgis:latest', 'qgis/qgis:ltr']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m venv /tmp/.venv --system-site-packages
          . /tmp/.venv/bin/activate
          python3 -m pip install -U pip setuptools uv
          python3 ./ci/dependency_installation.py
          python3 -m uv pip install -r test/requirements-test.txt --constraint ./ci/constraints.txt
          export PYTHONPATH=$(pwd)/qaequilibrae/packages:$PYTHONPATH
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV

      - name: Run tests
        run: |
          . /tmp/.venv/bin/activate
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest --cov-config=.coveragerc --cov-report term-missing --cov=qaequilibrae test
