name: DevelopmentTests

on:  [pull_request]

jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # container: ['qgis/qgis:latest', 'qgis/qgis:3.34.7']
        container: ['qgis/qgis:latest']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            python3 -m venv venv
            ls -d */

      # - name: Run tests
      #   run: |
      #     export QT_QPA_PLATFORM=offscreen
      #     pwd
