name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # container: [ 'qgis/qgis:release-3_34']
        container: [ 'qgis/qgis:latest', 'qgis/qgis:release-3_34']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies for Release
        if: ${{ (matrix.container == 'qgis/qgis:release-3_34')}}
        run: |
          python3 -m pip install setuptools
          python3 -m pip install -r test/requirements-test.txt
          python3 -m pip install -r ci/requirements-dev.txt
          python3 ./ci/dependency_installation.py

      - name: Install dependencies for Latest
        if: ${{ (matrix.container == 'qgis/qgis:latest')}}
        run: |
          python3 -m pip install setuptools --break-system-packages
          python3 -m pip install -r test/requirements-test.txt --break-system-packages
          python3 -m pip install -r ci/requirements-dev.txt --break-system-packages
          python3 ./ci/dependency_installation.py

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest test -v --tb=short --cov=qaequilibrae
