name: DevelopmentTests

on:  [pull_request]


jobs:
  unittest:
#    needs: linting
    runs-on: [ubuntu-latest, windows-latest]
    strategy:
      max-parallel: 4
      matrix:
        container: [ 'qgis/qgis:latest', 'qgis/qgis:3.34.7']
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m venv /tmp/venv_test --system-site-package
          . /tmp/venv_test/bin/activate
          python3 -m pip install setuptools
          python3 -m pip install -r test/requirements-test.txt
          python3 ./ci/dependency_installation.py
          export PYTHONPATH=$(pwd)/qaequilibrae/packages:$PYTHONPATH
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV

      - name: Run tests
        run: |
          . /tmp/venv_test/bin/activate
          export QT_QPA_PLATFORM=offscreen
          pwd
          python3 -m pytest test -v --tb=short --cov=qaequilibrae

  windows_test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install QGIS on Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install qgis-ltr -y --version 3.34.9

      - name: Plugin install
        shell: pwsh
        run: |
          $env:PATH="C:\Program Files\QGIS 3.34.9\bin;$env:PATH"
          $env:QGIS_PLUGIN_IN_CI=1
          pwd
          
  #         python-qgis-ltr.bat -m pip install -r test/requirements-test.txt
  #         python-qgis-ltr.bat ci/dependency_installation.py
  #         python-qgis-ltr.bat -m pip list
  #         python-qgis-ltr.bat -m pytest test -v --tb=short --cov=qaequilibrae
          