name: Documentation

on:
  push:
    branches:
      - develop
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --fix-missing latexmk texlive-latex-extra
        python -m pip install -U pip
        pip install -r docs/requirements-docs.txt

    - name: Prepare links for DEV
      if: ${{ (github.event_name == 'pull_request')}}
      run: |
        python -c "from ci.replace_regex import replace_regex; replace_regex('dev')"

    - name: Prepare links for DEVELOP
      if: ${{ (github.ref == 'refs/heads/develop') && (github.event_name == 'push')}}
      run: |
        python -c "from ci.replace_regex import replace_regex; replace_regex('develop')"

    - name: Build documentation
      run: |
        cp qaequilibrae/large_icon.png docs/source/_static/large_icon.png
        sphinx-build -M latexpdf docs/source docs/source/_static
        cd docs
        make html

    - name: Upload to DEV on S3
      if: ${{ (github.event_name == 'pull_request')}}
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'docs/build/html/'      # optional: defaults to entire repository
        DEST_DIR: 'dev/qgis/'      # optional: defaults to entire repository

    - name: Upload to DEVELOP on S3
      if: ${{ (github.ref == 'refs/heads/develop') && (github.event_name == 'push')}}
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'docs/build/html/'      # optional: defaults to entire repository
        DEST_DIR: 'develop/qgis/'
  
    - name: Upload to LATEST on S3
      if: ${{ (github.event_name == 'release')}}
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'docs/build/html/'      # optional: defaults to entire repository
        DEST_DIR: 'latest/qgis/'      # optional: defaults to entire repository

    - name: Upload documentation to history folder
      if: ${{ (github.event_name == 'release')}}
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'docs/build/html/'      # optional: defaults to entire repository
        DEST_DIR: 'docs/qgis/github.event.release.tag_name/'      # optional: defaults to entire repository