name: Packaging

on:
  push:
    branches:
      - develop
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install qgis-plugin-ci
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/packaging.txt

  packaging:
  needs: translation
  runs-on: ubuntu-latest
  steps:
    - name: Build artifact
      run: |
        mkdir -p /tmp/artifacts
        cd ..
    - name: build the package
      run: |
        qgis-plugin-ci package ${{ github.ref_name }}

    - uses: actions/upload-artifact@v3
      with:
        name: QAequilibraE
        path: /tmp/artifacts/*.zip
        if-no-files-found: error
