name: VersionRelease

env:
  PLUGIN_VERSION: $(python qaequilibrae/get_version.py)

on:
  push:
    branches: [develop]
  pull_request:
  release:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    
    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
  
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
  
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt install qttools5-dev-tools
        python -m pip install -U pip qgis-plugin-ci
    
    - name: Compile translations if they exist
      run: |
        lrelease qaequilibrae/i18n/qaequilibrae_*.ts
        sed -i "s|^*.qm.*| |" .gitignore
        git add qaequilibrae/

    - name: Build the package
      run: qgis-plugin-ci package ${{ env.PLUGIN_VERSION }} -c

    - name: Download artifact
      uses: actions/upload-artifact@v4
      with:
        name: qaequilibrae
        path: /home/runner/work/qaequilibrae/qaequilibrae/*.zip
        if-no-files-found: warn
  
    - name: Release plugin in QGIS
      if: ${{ (github.event_name == 'release')}}
      run: >-
        qgis-plugin-ci release ${{ env.PLUGIN_VERSION }} 
        --github-token ${{ secrets.GITHUB_TOKEN }} -c 
        --osgeo-username ${{ secrets.QGIS_PLUGIN_REPO_USER }} 
        --osgeo-password ${{ secrets.QGIS_PLUGIN_REPO_PASSWORD }}
        --create-plugin-repo
