name: VersionRelease

on:
  push:
    branches: [develop]
  pull_request:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    
    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
  
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
  
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt install qttools5-dev-tools
        python -m pip install -U pip qgis-plugin-ci
    
    - name: Compile translations if they exist
      run: |
        lrelease qaequilibrae/i18n/qaequilibrae_*.ts
        sed -i "s|^*.qm.*| |" .gitignore
        git add qaequilibrae/

    - name: Update version and SHA info
      run: python -c "from qaequilibrae.set_version import set_version; set_version('${{ github.event.pull_request.head.sha }}')"
    
    - name: Get plugin version
      run: |
        OUTPUT=$(python qaequilibrae/get_version.py)
        echo "PLUGIN_VERSION=$OUTPUT" >> $GITHUB_ENV
        echo "FILE_PATH=/home/runner/work/qaequilibrae/qaequilibrae/qaequilibrae.$OUTPUT.zip" >> $GITHUB_ENV

    - name: Build the package
      if: ${{ (github.event_name != 'release')}}
      run: qgis-plugin-ci package ${{ env.PLUGIN_VERSION }} -c

    - name: Download artifact
      if: ${{ (github.event_name != 'release')}}
      uses: actions/upload-artifact@v4
      with:
        name: qaequilibrae
        path: ${{ env.FILE_PATH }}
        if-no-files-found: warn

    - name: Upload ZIP to history on DEVELOP
      if: ${{ (github.ref == 'refs/heads/develop') && (github.event_name == 'push')}}
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --exclude '*' --include 'qaequilibrae*.zip'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        DEST_DIR: 'develop/qgis/version_history/'

    - name: Copy file to DOCS
      if: ${{ (github.ref == 'refs/heads/develop') && (github.event_name == 'push')}}
      run: |
        cp qaequilibrae*.zip docs/source/_static/qaequilibrae.zip

    - name: Upload ZIP to DEVELOP
      if: ${{ (github.ref == 'refs/heads/develop') && (github.event_name == 'push')}}
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --exclude '*' --include 'qaequilibrae.zip' --include 'plugin.xml'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'docs/source/_static/'
        DEST_DIR: 'develop/qgis/_static/'

    - name: Release plugin in QGIS
      if: ${{ (github.event_name == 'release')}}
      run: >-
        qgis-plugin-ci release ${{ env.PLUGIN_VERSION }}
        --release-tag ${{ github.event.release.tag_name }} 
        --github-token ${{ secrets.GITHUB_TOKEN }} 
        -r
        -c
        --osgeo-username ${{ secrets.QGIS_PLUGIN_REPO_USER }} 
        --osgeo-password ${{ secrets.QGIS_PLUGIN_REPO_PASSWORD }}
