name: translation

on:
  push:
    branches:
      - develop
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
  
    - name: Install Qt lrelease
      run: |
        sudo apt-get update
        sudo apt-get install qt5-qmake qttools5-dev-tools

    - name: Create translatable file
      run: |
        pylupdate5 -noobsolete qaequilibrae/i18n/qaequilibrae.pro

    - name: Install qgis-plugin-ci
      run: |
        python -m pip install --upgrade pip
        pip install qgis-plugin-ci

    - name: Push to Transifex
      run: |
        qgis-plugin-ci push-translation ${{ secrets.TX_TOKEN }}
  
    - name: Pull from Transifex
      run: |
        qgis-plugin-ci pull-translation --compile ${{ secrets.TX_TOKEN }}

    # - name: Deploy plugin
    #   run: >-
    #     qgis-plugin-ci
    #     release ${GITHUB_REF/refs\/tags\//}
    #     --transifex-token ${{ secrets.TX_TOKEN }}
    #     --github-token ${{ secrets.GITHUB_TOKEN }}
    #     --osgeo-username ${{ secrets.OSGEO_USER }}
    #     --osgeo-password ${{ secrets.OSGEO_PASSWORD }}