name: translate & pack

on:
  push:
    branches:
      - develop
  pull_request:
  release:

jobs:
  translation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
  
    - name: Install Qt lrelease
      run: |
        sudo apt-get update
        sudo apt-get install qt5-qmake qttools5-dev-tools

    - name: Create translatable file
      run: |
        lupdate -no-obsolete qaequilibrae/i18n/qaequilibrae.pro

    - name: Install qgis-plugin-ci
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/packaging.txt

    # - name: Push to Transifex
    #   run: |
    #     qgis-plugin-ci push-translation ${{ secrets.TX_TOKEN }}
  
    - name: Pull from Transifex
      run: |
        qgis-plugin-ci pull-translation --compile ${{ secrets.TX_TOKEN }}

    - name: build the package
      run: |
        qgis-plugin-ci package 0.0.1 -c

    - name: Download artifact
      uses: actions/upload-artifact@v3
      with:
        name: qaequilibrae
        path: /home/runner/work/qaequilibrae/qaequilibrae/*.zip
        if-no-files-found: error
  
    # - name: Deploy plugin
    #   run: >-
    #     qgis-plugin-ci
    #     release ${GITHUB_REF/refs\/tags\//}
    #     --transifex-token ${{ secrets.TX_TOKEN }}
    #     --github-token ${{ secrets.GITHUB_TOKEN }}
    #     --osgeo-username ${{ secrets.OSGEO_USER }}
    #     --osgeo-password ${{ secrets.OSGEO_PASSWORD }}