name: translate & pack

env:
  PLUGIN_VERSION: $(python get_version.py)
  PROJECT_FOLDER: "qaequilibrae"

on:
  push:
    branches:
      - develop
  pull_request:
  release:

jobs:
  translation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
  
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt install qttools5-dev-tools
        python -m pip install --upgrade pip
        python -m pip install -r requirements/packaging.txt
    
    - name: Create pro file
      run: python qaequilibrae/i18n/create_pro_file.py

    - name: Create translatable file
      run: pylupdate5 qaequilibrae/i18n/qaequilibrae.pro
    
    - id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file  with the .pro extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object {$_ -match '.pro$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "pro_changed"
        Write-Host "::set-output name=pro_changed::$HasDiff"

    - name: Check if translatable file has changed
      if: steps.check_file_changed.outputs.pro_changed == 'True'
      run: echo "The .pro file compiled has differences."
  
    # - name: Update translatable file
    #   run: |
    #     git add ${{ env.PROJECT_FOLDER }}/i18n/qaequilibrae.ts
    #     git commit -m "Update translatable file"
    
    # - name: Push changes to TS file
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: B77 #ignore if your branch is master
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     force: true

    - name: Compile translations
      run: lrelease ${{ env.PROJECT_FOLDER}}/i18n/qaequilibrae_*.ts

    - name: Amend gitignore to include compiled translations and add it to tracked files
      run: |
        sed -i "s|^*.qm.*| |" .gitignore
        git add ${{ env.PROJECT_FOLDER }}/
  
    - name: Build the package
      run: qgis-plugin-ci package ${{ env.PLUGIN_VERSION }} -c

    - name: Download artifact
      uses: actions/upload-artifact@v3
      with:
        name: qaequilibrae
        path: /home/runner/work/qaequilibrae/qaequilibrae/*.zip
        if-no-files-found: error
  
    # - name: Deploy plugin
    #   if: ${{ (github.event_name == 'release')}}
    #   run: >-
    #     qgis-plugin-ci
    #     release ${GITHUB_REF/refs\/tags\//}
    #     --github-token ${{ secrets.GITHUB_TOKEN }}
    #     --osgeo-username ${{ secrets.QGIS_PLUGIN_REPO_USER }}
    #     --osgeo-password ${{ secrets.QGIS_PLUGIN_REPO_PASSWORD }}