name: translate & pack

env:
  PLUGIN_VERSION: 0.9.0.1
  PROJECT_FOLDER: "qaequilibrae"

on:
  push:
    branches:
      - develop
  pull_request:
  release:

jobs:
  translation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
  
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt install qttools5-dev-tools
        python -m pip install --upgrade pip
        python -m pip install -r requirements/packaging.txt

    # - name: Create translatable file
    #   run: |
    #     lupdate -no-obsolete qaequilibrae/i18n/qaequilibrae.pro

    # - name: Push to Transifex
    #   run: |
    #     qgis-plugin-ci push-translation ${{ secrets.TX_TOKEN }}
  
    # - name: Pull from Transifex
    #   run: |
    #     qgis-plugin-ci pull-translation --compile ${{ secrets.TX_TOKEN }}

    - name: Compile translations
      run:  |
        lrelease ${{ env.PROJECT_FOLDER}}/i18n/*.ts

    - name: build the package
      run: |
        qgis-plugin-ci package ${{ env.PLUGIN_VERSION }} -c

    - name: Download artifact
      uses: actions/upload-artifact@v3
      with:
        name: qaequilibrae
        path: /home/runner/work/qaequilibrae/qaequilibrae/*.zip
        if-no-files-found: error
  
    # - name: Deploy plugin
    #   if: ${{ (github.event_name == 'release')}}
    #   run: >-
    #     qgis-plugin-ci
    #     release ${GITHUB_REF/refs\/tags\//}
    #     --transifex-token ${{ secrets.TX_TOKEN }}
    #     --github-token ${{ secrets.GITHUB_TOKEN }}
    #     --osgeo-username ${{ secrets.QGIS_PLUGIN_REPO_USER }}
    #     --osgeo-password ${{ secrets.QGIS_PLUGIN_REPO_PASSWORD }}