name: TranslationFilesCheck

env:
  VALIDATE_FILE: "is_file"

on:
  push:
    branches: [develop]

jobs:
  translation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v7
      with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v7
      with:
        python-version: 3.12

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt install qttools5-dev-tools
        python -m pip install -U pip qgis-plugin-ci
    
    - name: Create translatable files
      run: |
        python qaequilibrae/i18n/create_pro_file.py
        pylupdate5 qaequilibrae/i18n/qaequilibrae.pro
        rm qaequilibrae/i18n/qaequilibrae.pro

    - name: Check if there are modifications in the translation files
      id: check-modifications
      run: |
        git fetch --no-tags --depth=1 origin develop
        files_changed=$(git diff --name-only)
      
        if echo "${files_changed}" | grep --quiet "qaequilibrae/i18n/qaequilibrae.ts"; then
          echo "is_file=is_file" >> "$GITHUB_OUTPUT"
        else
          echo "Translation file wasn't modified."
        fi
    
    - name: Create PR
      if: ${{ steps.check-modifications.outputs.is_file == env.VALIDATE_FILE }}
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: Update translation file
        title: Updates translation file
        body: |
          This PR updates the contents in the main translatable file (_qaequilibrae/i18n/qaequilibrae.ts_).
          
          Auto-generated by [create-pull-request][1].
  
          [1]: https://github.com/peter-evans/create-pull-request
        branch: update-ts
