name: WindowsReleaseTest

on:  
  pull_request:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  windows_test:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [qgis]

    steps:
      - uses: actions/checkout@v3
      
      - name: Install QGIS on Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install ${{ matrix.version }} -y

      - name: Setup plugin
        shell: pwsh
        run: |
          Copy-Item "qaequilibrae" -Destination "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae" -Recurse
        # $env:PATH=(Get-ChildItem -Path "C:\Program Files" -Directory QGIS*).FullName +"\bin;$env:PATH"
          $env:QGIS_PLUGIN_IN_CI=1
          Get-ChildItem -Path "C:\Program Files\QGIS*\bin\*.bat" -Name

      - name: Install pytest on Latest
        shell: pwsh
        if: ${{ (matrix.version == 'qgis')}}
        run: |
          $qgisPath = (Get-ChildItem -Path "C:\Program Files" -Directory QGIS*).FullName
          $env:PATH = "$qgisPath\bin;$qgisPath\apps\Python*\Scripts;$env:PATH"
          "$qgisPath\apps\Python*\python.exe" -m pip install -r test/requirements-test.txt
      
      - name: Set Location
        shell: pwsh
        run: Set-Location "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae"

      # - name: Install plugin on LTR
      #   shell: pwsh
      #   if: ${{ (matrix.version != 'qgis')}}
      #   run: |
      #     python-qgis-ltr.bat download_extra_packages_class.py
          
      - name: Install plugin on Latest
        shell: pwsh
        if: ${{ (matrix.version == 'qgis')}}
        run: |
          "$qgisPath\apps\Python*\python.exe" download_extra_packages_class.py

      - name: Run tests
        shell: pwsh
        run: |
          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages" -Name