name: WindowsReleaseTest

on:
  push:
    branches: [develop]
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  windows_test:
    runs-on: windows-latest
    # strategy:
    #   matrix:
    #   # we test the minimum LTR version required, the newest LTR, and the latest.
    #   # version: [qgis-ltr --version=3.34.10, qgis-ltr, qgis]
    #   version: [qgis]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install QGIS on Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install qgis -y

      - name: Setup plugin on Latest
        shell: pwsh
        run: |
          Copy-Item "qaequilibrae" -Destination "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae" -Recurse
          Copy-Item "test" -Destination "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\test" -Recurse
          $qgisPath = (Get-ChildItem -Path "C:\Program Files" -Filter "QGIS*" -Directory).FullName
          echo "$qgisPath\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          $env:QGIS_PREFIX_PATH = $qgisPath
          $env:PYTHONPATH = "$qgisPath\apps\qgis\python"
          $env:QT_QPA_PLATFORM = "offscreen"
          Set-Location "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae"
          python-qgis.bat download_extra_packages_class.py
          python-qgis.bat -m uv pip install -r test/requirements-test.txt --target "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages"
        # python-qgis.bat -m pytest test -v

      - name: Check installation
        shell: pwsh
        run: |
          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages" -Name
