name: WindowsReleaseTest

on:  
  pull_request:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  windows_test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install QGIS on Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install qgis-ltr -y

      - name: Plugin install
        shell: pwsh
        run: |
          $env:PATH=(Get-ChildItem -Path "C:\Program Files" -Directory QGIS*).FullName +"\bin;$env:PATH"
          Copy-Item "qaequilibrae" -Destination "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae" -Recurse
          $env:QGIS_PLUGIN_IN_CI=1
          python-qgis-ltr.bat -m pip install -r test/requirements-test.txt
          python-qgis-ltr.bat -m pip list
          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins"
          Set-Location "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae"
          python-qgis-ltr.bat start_download.py
          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages"
        # python-qgis-ltr.bat -m pip list
        # python-qgis-ltr.bat -m pytest test -v --tb=short --cov=qaequilibrae
          