name: WindowsReleaseTest

on:  
  pull_request:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  windows_test:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [qgis-ltr --version=3.34.6, qgis-ltr, qgis --version=3.38.0]

    steps:
      - uses: actions/checkout@v3
      
      - name: Install QGIS on Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install ${{ matrix.version }} -y

      - name: Setup plugin
        shell: pwsh
        run: |
          Copy-Item "qaequilibrae" -Destination "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae" -Recurse
          $env:PATH=(Get-ChildItem -Path "C:\Program Files" -Directory QGIS*).FullName +"\bin;$env:PATH"
          $env:QGIS_PLUGIN_IN_CI=1
          Get-ChildItem -Path "$env:PATH"
          Set-Location "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae"

      - name: Install plugin on LTR
        shell: pwsh
        if: ${{ (matrix.version != 'qgis --version=3.38.0')}}
        run: |
          python-qgis-ltr.bat download_extra_packages_class.py
          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages"

        - name: Install plugin on Latest
          shell: pwsh
          if: ${{ (matrix.version == 'qgis --version=3.38.0')}}
          run: |
            python-qgis.bat download_extra_packages_class.py
            Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages