name: WindowsReleaseTest

on:  
  pull_request:
  schedule:
    - cron: '15 * * * *'

jobs:
  windows_test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install QGIS on Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install qgis-ltr --version=3.34.4 -y

      - name: Plugin install
        shell: pwsh
        run: |
          Copy-Item "qaequilibrae" -Destination "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae" -Recurse
          $env:PATH=(Get-ChildItem -Path "C:\Program Files" -Directory QGIS*).FullName +"\bin;$env:PATH"
          $env:QGIS_PLUGIN_IN_CI=1
          Set-Location "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae"
          python-qgis-ltr.bat download_extra_packages_class.py
          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages"
