name: WindowsReleaseTest

on:
  push:
    branches: [develop]
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  windows_test:
    runs-on: windows-latest
    # strategy:
    #   matrix:
    #   # we test the minimum LTR version required, the newest LTR, and the latest.
    #   # version: [qgis-ltr --version=3.34.10, qgis-ltr, qgis]
    #   version: [qgis]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install QGIS on Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install qgis -y

      - name: Setup plugin on Latest
        shell: pwsh
        run: |
          Copy-Item "qaequilibrae" -Destination "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae" -Recurse
          Copy-Item "test" -Destination "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\test" -Recurse
          $env:PATH=(Get-ChildItem -Path "C:\Program Files" -Directory QGIS*).FullName +"\bin;$env:PATH"
          $env:QGIS_PLUGIN_IN_CI=1
          Set-Location "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae"
          python-qgis.bat download_extra_packages_class.py
          python-qgis.bat -m pip install -r test/requirements-test.txt
          python-qgis.bat -m pip list
          $env:QT_QPA_PLATFORM = "offscreen"
          python-qgis.bat -m pytest D:\a\qaequilibrae\qaequilibrae\test -v

      - name: Check installation
        shell: pwsh
        run: |
          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae\packages" -Name
