name: WindowsReleaseTest

on:
  push:
    branches: [develop]
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  windows_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            DOCKERFILE: .devcontainer/Dockerfile-qgis
            BASE_OS: servercore-ltsc2022

    steps:
      - uses: actions/checkout@v4
  
      # Currently skipping tests with relative path to test folder
      - name: Setup and test plugin on LTR
        shell: pwsh
        run: |
          Get-ChildItem env:
