name: WindowsReleaseTest

on:
  push:
    branches: [develop]
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  windows_test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install QGIS on Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install qgis -y

      # we can run the tests, but they're timing out (and I don't know why...)
      - name: Setup plugin on Latest
        shell: pwsh
        run: |
          $qgisPath = (Get-ChildItem -Path "C:\Program Files" -Filter "QGIS*" -Directory).FullName
          $qgisExec = "$qgisPath\bin\python-qgis.bat"
          $aeqPath = "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae"
          $localPath = pwd
          Copy-Item "qaequilibrae" -Destination "$aeqPath" -Recurse
          $env:PYTHONPATH = "$qgisPath\apps\qgis\python"
          $env:QT_QPA_PLATFORM = "offscreen"
          Start-Process -FilePath "$qgisExec" -ArgumentList "-m pip install -r test/requirements-test.txt" -NoNewWindow -Wait
          Set-Location "$aeqPath"
          Start-Process -FilePath "$qgisExec" -ArgumentList "download_extra_packages_class.py" -NoNewWindow -Wait
          $env:PYTHONPATH = "$env:PYTHONPATH;APPDATA\QGIS\QGIS3\profiles\default\python\plugins"
          Set-Location "$localPath"
          Start-Process -FilePath "$qgisExec" -ArgumentList "-m pytest test" -NoNewWindow -Wait

      - name: Check packages installed
        shell: pwsh
        run: |
          Get-ChildItem -Path "$env:APPDATA\QGIS\QGIS3\profiles\default\python\plugins\qaequilibrae" -Name